### ISSUE TITLE
Some glyphs dropped

### ISSUE THREAD

**Issue by simoncozens** [googlei18n/fontmake#114]
I'm making a mainly monoline font and one of my masters has open paths. I don't use this master for interpolation, but just having the master in the .glyphs file means that some but not all glyphs become empty. (By empty I mean the outline is just`0 endchar`) If I remove the master and save as a separate .glyphs file, the glyphs convert just fine.

I am not sure why it's certain glyphs but not others.

![video](https://cloud.githubusercontent.com/assets/106728/17234466/afd8cc6e-557c-11e6-8de3-262607bdb78c.png)

**Comment by behdad** [comment]
Interesting.

**Comment by jamesgk** [comment]
Very strange. It would be helpful for debugging if you could provide some source, even just a small example where this problem shows up.

**Comment by simoncozens** [comment]
Can I mail it to you? I tried making a Glyphs file with just a couple of affected characters, but when I try to use that, I get a different issue:

    > Checking Glyphs source for illegal glyph names
    >> Building UFOs from Glyphs source
    >>> Parsing .glyphs file
    >>> Casting parsed values
    >>> Loading to UFOs
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/fontmake/__main__.py", line 92, in <module>
        main()
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/fontmake/__main__.py", line 77, in main
        project.run_from_glyphs(glyphs_path, **args)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/fontmake/font_project.py", line 266, in run_from_glyphs
        glyphs_path, interpolate, masters_as_instances, family_name)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/FontTools/fontTools/misc/loggingTools.py", line 372, in wrapper
        return func(*args, **kwds)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/fontmake/font_project.py", line 92, in build_ufos
        glyphs_path, master_dir, instance_dir, family_name=family_name))
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/glyphsLib/__init__.py", line 97, in build_instances
        filename, include_instances=True, family_name=family_name)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/glyphsLib/__init__.py", line 60, in load_to_ufos
        family_name=family_name, debug=debug)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/glyphsLib/builder.py", line 143, in to_ufos
        propagate_font_anchors(ufo)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/glyphsLib/anchors.py", line 29, in propagate_font_anchors
        propagate_glyph_anchors(ufo, glyph, processed)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/glyphsLib/anchors.py", line 44, in propagate_glyph_anchors
        glyph = ufo[component.baseGlyph]
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/defcon/objects/font.py", line 216, in __getitem__
        return self._glyphSet[name]
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/defcon/objects/layer.py", line 260, in __getitem__
        self.loadGlyph(name)
      File "/Users/simon/others-repos/fontmake/env/lib/python2.7/site-packages/defcon/objects/layer.py", line 177, in loadGlyph
        raise KeyError("%s not in layer" % name)

**Comment by jamesgk** [comment]
So what's happening here is that fontmake always includes all masters in its MutatorMath designspace, and even if a master has parameters such that it won't affect interpolation at all, I guess MutatorMath still needs it to be interpolation-compatible with other masters or else weird stuff like this happens.

One fix would be to check if a master wouldn't be used for interpolation, and exclude it if that's the case. Another might be to fix something in MutatorMath itself.

**Comment by davelab6** [comment]
>
> check if a master wouldn't be used for interpolation


Sounds good to me :)

**Comment by simoncozens** [comment]
Another couple of ways to fix would be to either allow the user to manually select which masters they care about, or (for my use case) for there to be a utility which could process glyphs files in arbitrary ways, eg stripping out / keeping selected masters. If we had a library for manipulating glyphs files that shouldn't be too tough a call...

**Comment by jamesgk** [comment]
> If we had a library for manipulating glyphs files

Of course, we do have such a library! https://github.com/googlei18n/glyphsLib
This can be used for loading Glyphs data into a Python dict, which you could trim masters from. Not sure how easy that would be though since every glyph would need the respective layers removed.

**Comment by brawer** [comment]
What’s the status of this bug?

**Comment by jamesgk** [comment]
This bug is still active, incompatible masters will still affect output even if they shouldn't affect interpolation.

**Comment by anthrotype** [comment]
> fontmake always includes all masters in its MutatorMath designspace, and even if a master has parameters such that it won't affect interpolation at all

hm, what's the point of having a master in there if it doesn't affect interpolation?

**Comment by simoncozens** [comment]
In my case, one of the masters was an open-path skeleton, which the other masters were derived from with offsetting filters. (Before I then made all the necessary optical corrections, naturally.) That was throwing things.

Also my bold master is very different to the semibold and there's no interpolation between the two.

**Comment by behdad** [comment]
One way would be to ask @schriftgestalt to add a property to disable masters from participating in interpolation.  Not sure how much sense that makes.

**Comment by anthrotype** [comment]
Could it be implicit? if there are no instances "in between" two masters, or if the instance location is the same as a master, then no interpolation should take place.

**Comment by behdad** [comment]
> Could it be implicit? if there are no instances "in between" two masters, or if the instance location is the same as a master, then no interpolation should take place.

Glyphs already has such implicit assumptions (not showing master incompatibility if there's no instance defined between two masters?) and that's already problematic for varfont workflow, which does not require named instances to be defined.

**Comment by schriftgestalt** [comment]
There is an parameter 'Ignore Master' already. 
I see the problem with not showing the incompatiblility for variation fonts. I'll fix this.

**Comment by anthrotype** [comment]
Thanks Georg! Yeah, I think we could use that custom parameter in fontmake as well...

**Comment by schriftgestalt** [comment]
I would treat an `Axes` parameter as key.
