### ISSUE TITLE
ufoLib.glifLib.GlifLibError: guidelines attribute does not have the proper structure while building src/NotoSansArabic-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#132]
I tried to compile src/NotoSansArabic-MM.glyphs (see https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs if you want the source) and got a unexpected error (I've never seen this before). Is my build an issue?

```
>>> Writing master_ufo/NotoSansArabic-CondensedBold.ufo
>>> Building instances
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 236, in run_from_glyphs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 82, in build_ufos
  File "build/bdist.linux-x86_64/egg/glyphsLib/__init__.py", line 102, in build_instances
  File "build/bdist.linux-x86_64/egg/glyphsLib/interpolation.py", line 45, in interpolate
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/mutatorMath/ufo/__init__.py", line 56, in build
    reader.process()
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/mutatorMath/ufo/document.py", line 415, in process
    self.readInstances(makeGlyphs=makeGlyphs, makeKerning=makeKerning, makeInfo=makeInfo)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/mutatorMath/ufo/document.py", line 570, in readInstances
    self._readSingleInstanceElement(instanceElement, makeGlyphs=makeGlyphs, makeKerning=makeKerning, makeInfo=makeInfo)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/mutatorMath/ufo/document.py", line 668, in _readSingleInstanceE
lement
    success, report = instanceObject.save()
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/mutatorMath/ufo/instance.py", line 385, in save
    self.font.save(self.path, self.ufoVersion)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/font.py", line 729, in save
    self.layers.save(writer, saveAs=saveAs, progressBar=progressBar)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/layerSet.py", line 318, in save
    layer.save(glyphSet, saveAs=saveAs, progressBar=progressBar)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/layer.py", line 606, in save
    self.saveGlyph(glyph, glyphSet, saveAs=saveAs)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/layer.py", line 622, in saveGlyph
    glyphSet.writeGlyph(glyph.name, glyph, glyph.drawPoints)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/ufoLib/glifLib.py", line 339, in writeGlyph
    data = writeGlyphToString(glyphName, glyphObject, drawPointsFunc, formatVersion=formatVersion)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/ufoLib/glifLib.py", line 559, in writeGlyphToString
    _writeGuidelines(glyphObject, writer, identifiers)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/ufoLib/glifLib.py", line 659, in _writeGuidelines
    raise GlifLibError("guidelines attribute does not have the proper structure.")
ufoLib.glifLib.GlifLibError: guidelines attribute does not have the proper structure.
```

**Comment by jamesgk** [comment]
MutatorMath is calculating negative guideline angles, which are illegal according to the UFO spec: http://unifiedfontobject.org/versions/ufo3/glyphs/glif/#guideline.

Not sure if this should be fixed in Defcon (just add 360 to any negative angle?), or fontMath (same fix), or if there's supposed to be something preventing this in MutatorMath that isn't working.
cc @adrientetar

**Comment by jamesgk** [comment]
I guess it doesn't make any sense for MutatorMath to calculate negative angles, assuming none of the masters have negative angles (which they shouldn't, since they are validated and saved successfully before interpolation). So I guess the correct fix is something in MutatorMath.

**Comment by jamesgk** [comment]
I pushed a small example Glyphs file with this same issue: https://github.com/googlei18n/fontmake/blob/master/test/GuidelineTest.glyphs

**Comment by marekjez86** [comment]
This appears to be fixed. I'm unable to reproduce this problem.
