### ISSUE TITLE
AssertionError while compiling src/NotoSansKhmer/NotoSansKhmer-MM.plist

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#134]
this is new so this could be a new bug or my bad build.

you can find the source in
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansKhmer/NotoSansKhmer-MM.plist

```
==== building src/NotoSansKhmer/NotoSansKhmer-MM.plist ====
>> Checking Glyphs source for illegal glyph names
>> Building UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 236, in run_from_glyphs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 85, in build_ufos
  File "build/bdist.linux-x86_64/egg/glyphsLib/__init__.py", line 79, in build_masters
  File "build/bdist.linux-x86_64/egg/glyphsLib/__init__.py", line 63, in load_to_ufos
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder.py", line 142, in to_ufos
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder.py", line 607, in load_glyph
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder.py", line 560, in load_glyph_libdata
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder.py", line 394, in set_guidelines
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/glyph.py", line 796, in _set_guidelines
    self.appendGuideline(guideline)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/glyph.py", line 825, in appendGuideline
    self.insertGuideline(len(self._guidelines), guideline)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/glyph.py", line 837, in insertGuideline
    assert guideline not in self.guidelines
AssertionError
```

**Comment by marekjez86** [comment]
unable to reproduce. right now I can build src/NotoSansKhmer/NotoSansKhmer-MM.plist
appears to be fixed
