### ISSUE TITLE
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 1)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#140]
Note NotoSansEthiopic-MM.glyphs is contained in this zip file 
[NotoSansEthiopic-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/440156/NotoSansEthiopic-MM.glyphs.zip)

My gut feeling is that this is the same/similar to https://github.com/googlei18n/fontmake/issues/139 (it just takes a long time to process the last step).

make -B -k -d src/NotoSansEthiopic-MM.glyphs
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Reading makefile `Makefile'...
Updating makefiles....
 Considering target file `Makefile'.
  Looking for an implicit rule for `Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.o'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.c'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.cc'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.C'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.cpp'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.p'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.f'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.F'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.m'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.r'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.s'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.S'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.sh'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile,v'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `RCS/Makefile,v'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `RCS/Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `s.Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `SCCS/s.Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.o'.
  Looking for a rule with intermediate file `Makefile.o'.
   Avoiding implicit rule recursion.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.c'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cc'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.C'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cpp'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.p'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.f'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.F'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.m'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.s'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.mod'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `Makefile.o,v'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `RCS/Makefile.o,v'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `RCS/Makefile.o'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `s.Makefile.o'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `SCCS/s.Makefile.o'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.c'.
   Looking for a rule with intermediate file `Makefile.c'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.y'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.l'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `Makefile.c,v'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `RCS/Makefile.c,v'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `RCS/Makefile.c'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `s.Makefile.c'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `SCCS/s.Makefile.c'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.y'.
    Looking for a rule with intermediate file `Makefile.y'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `Makefile.y,v'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `RCS/Makefile.y,v'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `RCS/Makefile.y'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `s.Makefile.y'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `SCCS/s.Makefile.y'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.l'.
    Looking for a rule with intermediate file `Makefile.l'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `Makefile.l,v'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `RCS/Makefile.l,v'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `RCS/Makefile.l'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `s.Makefile.l'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `SCCS/s.Makefile.l'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Looking for a rule with intermediate file `Makefile.w'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `Makefile.w,v'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `RCS/Makefile.w,v'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `RCS/Makefile.w'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `s.Makefile.w'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `SCCS/s.Makefile.w'.
    Trying pattern rule with stem `Makefile'.
    Rejecting impossible implicit prerequisite `Makefile.w'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cc'.
   Looking for a rule with intermediate file `Makefile.cc'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `Makefile.cc,v'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `RCS/Makefile.cc,v'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `RCS/Makefile.cc'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `s.Makefile.cc'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `SCCS/s.Makefile.cc'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.C'.
   Looking for a rule with intermediate file `Makefile.C'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `Makefile.C,v'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `RCS/Makefile.C,v'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `RCS/Makefile.C'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `s.Makefile.C'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `SCCS/s.Makefile.C'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cpp'.
   Looking for a rule with intermediate file `Makefile.cpp'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `Makefile.cpp,v'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `RCS/Makefile.cpp,v'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `RCS/Makefile.cpp'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `s.Makefile.cpp'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `SCCS/s.Makefile.cpp'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.p'.
   Looking for a rule with intermediate file `Makefile.p'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.web'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `Makefile.p,v'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `RCS/Makefile.p,v'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `RCS/Makefile.p'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `s.Makefile.p'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `SCCS/s.Makefile.p'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.web'.
    Looking for a rule with intermediate file `Makefile.web'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `Makefile.web,v'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `RCS/Makefile.web,v'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `RCS/Makefile.web'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `s.Makefile.web'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `SCCS/s.Makefile.web'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.f'.
   Looking for a rule with intermediate file `Makefile.f'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.F'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.r'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `Makefile.f,v'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `RCS/Makefile.f,v'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `RCS/Makefile.f'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `s.Makefile.f'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `SCCS/s.Makefile.f'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.F'.
    Looking for a rule with intermediate file `Makefile.F'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `Makefile.F,v'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `RCS/Makefile.F,v'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `RCS/Makefile.F'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `s.Makefile.F'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `SCCS/s.Makefile.F'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.r'.
    Looking for a rule with intermediate file `Makefile.r'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile'.
     Rejecting impossible implicit prerequisite `Makefile.l'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `Makefile.r,v'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `RCS/Makefile.r,v'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `RCS/Makefile.r'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `s.Makefile.r'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `SCCS/s.Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.F'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.m'.
   Looking for a rule with intermediate file `Makefile.m'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.ym'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.lm'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `Makefile.m,v'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `RCS/Makefile.m,v'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `RCS/Makefile.m'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `s.Makefile.m'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `SCCS/s.Makefile.m'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.ym'.
    Looking for a rule with intermediate file `Makefile.ym'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `Makefile.ym,v'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `RCS/Makefile.ym,v'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `RCS/Makefile.ym'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `s.Makefile.ym'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `SCCS/s.Makefile.ym'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.lm'.
    Looking for a rule with intermediate file `Makefile.lm'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `Makefile.lm,v'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `RCS/Makefile.lm,v'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `RCS/Makefile.lm'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `s.Makefile.lm'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `SCCS/s.Makefile.lm'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.s'.
   Looking for a rule with intermediate file `Makefile.s'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.S'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `Makefile.s,v'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `RCS/Makefile.s,v'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `RCS/Makefile.s'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `s.Makefile.s'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `SCCS/s.Makefile.s'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.S'.
    Looking for a rule with intermediate file `Makefile.S'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `Makefile.S,v'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `RCS/Makefile.S,v'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `RCS/Makefile.S'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `s.Makefile.S'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `SCCS/s.Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.mod'.
   Looking for a rule with intermediate file `Makefile.mod'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `Makefile.mod,v'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `RCS/Makefile.mod,v'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `RCS/Makefile.mod'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `s.Makefile.mod'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `SCCS/s.Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.c'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.cc'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.C'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.cpp'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.p'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.f'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.F'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.m'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.r'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.s'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.S'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.sh'.
  Looking for a rule with intermediate file `Makefile.sh'.
   Avoiding implicit rule recursion.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `Makefile.sh,v'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `RCS/Makefile.sh,v'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `RCS/Makefile.sh'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `s.Makefile.sh'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `SCCS/s.Makefile.sh'.
  No implicit rule found for `Makefile'.
  Finished prerequisites of target file `Makefile'.
 No need to remake target `Makefile'.
Updating goal targets....
Considering target file `src/NotoSansEthiopic-MM.glyphs'.
 Looking for an implicit rule for `src/NotoSansEthiopic-MM.glyphs'.
 Trying pattern rule with stem `NotoSansEthiopic-MM.glyphs'.
 Found an implicit rule for `src/NotoSansEthiopic-MM.glyphs'.
 Finished prerequisites of target file `src/NotoSansEthiopic-MM.glyphs'.
Making `src/NotoSansEthiopic-MM.glyphs' due to always-make flag.
Must remake target `src/NotoSansEthiopic-MM.glyphs'.
bash build.sh build_one src/NotoSansEthiopic-MM.glyphs
Putting child 0x7fabd2504a30 (src/NotoSansEthiopic-MM.glyphs) PID 75307 on the chain.
Live child 0x7fabd2504a30 (src/NotoSansEthiopic-MM.glyphs) PID 75307 
>> Checking Glyphs source for illegal glyph names
>> Building UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
>>> Writing master_ufo/NotoSansEthiopic-Light.ufo
>>> Writing master_ufo/NotoSansEthiopic-Regular.ufo
>>> Writing master_ufo/NotoSansEthiopic-SemiBold.ufo
>>> Writing master_ufo/NotoSansEthiopic-Bold.ufo
>>> Writing master_ufo/NotoSansEthiopic-CondensedLight.ufo
>>> Writing master_ufo/NotoSansEthiopic-Condensed.ufo
>>> Writing master_ufo/NotoSansEthiopic-CondensedSemiBold.ufo
>>> Writing master_ufo/NotoSansEthiopic-CondensedBold.ufo
>>> Building instances

>> Building OTFs
>> Decomposing glyphs for NotoSansEthiopic-Thin
>> Decomposing glyphs for NotoSansEthiopic-ExtraLight
>> Decomposing glyphs for NotoSansEthiopic-Light
>> Decomposing glyphs for NotoSansEthiopic-Regular
>> Decomposing glyphs for NotoSansEthiopic-Medium
>> Decomposing glyphs for NotoSansEthiopic-SemiBold
>> Decomposing glyphs for NotoSansEthiopic-Bold
>> Decomposing glyphs for NotoSansEthiopic-ExtraBold
>> Decomposing glyphs for NotoSansEthiopic-Black
>> Decomposing glyphs for NotoSansEthiopic-CondensedThin
>> Decomposing glyphs for NotoSansEthiopic-CondensedExtraLight
>> Decomposing glyphs for NotoSansEthiopic-CondensedLight
>> Decomposing glyphs for NotoSansEthiopic-Condensed
>> Decomposing glyphs for NotoSansEthiopic-CondensedMedium
>> Decomposing glyphs for NotoSansEthiopic-CondensedSemiBold
>> Decomposing glyphs for NotoSansEthiopic-CondensedBold
>> Decomposing glyphs for NotoSansEthiopic-CondensedExtraBold
>> Decomposing glyphs for NotoSansEthiopic-CondensedBlack
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedThin
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedExtraLight
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedLight
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensed
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedMedium
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedSemiBold
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedBold
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedExtraBold
>> Decomposing glyphs for NotoSansEthiopic-SemiCondensedBlack
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedThin
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedExtraLight
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedLight
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensed
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedMedium
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedSemiBold
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedBold
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedExtraBold
>> Decomposing glyphs for NotoSansEthiopic-ExtraCondensedBlack
>> Removing overlaps for NotoSansEthiopic-Thin
>> Removing overlaps for NotoSansEthiopic-ExtraLight
>> Removing overlaps for NotoSansEthiopic-Light
>> Removing overlaps for NotoSansEthiopic-Regular
>> Removing overlaps for NotoSansEthiopic-Medium
>> Removing overlaps for NotoSansEthiopic-SemiBold
>> Removing overlaps for NotoSansEthiopic-Bold
>> Removing overlaps for NotoSansEthiopic-ExtraBold
>> Removing overlaps for NotoSansEthiopic-Black
>> Removing overlaps for NotoSansEthiopic-CondensedThin
>> Removing overlaps for NotoSansEthiopic-CondensedExtraLight
>> Removing overlaps for NotoSansEthiopic-CondensedLight
>> Removing overlaps for NotoSansEthiopic-Condensed
>> Removing overlaps for NotoSansEthiopic-CondensedMedium
>> Removing overlaps for NotoSansEthiopic-CondensedSemiBold
>> Removing overlaps for NotoSansEthiopic-CondensedBold
>> Removing overlaps for NotoSansEthiopic-CondensedExtraBold
>> Removing overlaps for NotoSansEthiopic-CondensedBlack
>> Removing overlaps for NotoSansEthiopic-SemiCondensedThin
>> Removing overlaps for NotoSansEthiopic-SemiCondensedExtraLight
>> Removing overlaps for NotoSansEthiopic-SemiCondensedLight
>> Removing overlaps for NotoSansEthiopic-SemiCondensed
>> Removing overlaps for NotoSansEthiopic-SemiCondensedMedium
>> Removing overlaps for NotoSansEthiopic-SemiCondensedSemiBold
>> Removing overlaps for NotoSansEthiopic-SemiCondensedBold
>> Removing overlaps for NotoSansEthiopic-SemiCondensedExtraBold
>> Removing overlaps for NotoSansEthiopic-SemiCondensedBlack
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedThin
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedExtraLight
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedLight
>> Removing overlaps for NotoSansEthiopic-ExtraCondensed
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedMedium
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedSemiBold
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedBold
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedExtraBold
>> Removing overlaps for NotoSansEthiopic-ExtraCondensedBlack
>> Saving OTF for NotoSansEthiopic-Thin
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.6-intel/egg/fontmake/__main__.py", line 89, in main
  File "build/bdist.macosx-10.6-intel/egg/fontmake/font_project.py", line 277, in run_from_glyphs
  File "build/bdist.macosx-10.6-intel/egg/fontmake/font_project.py", line 329, in run_from_ufos
  File "build/bdist.macosx-10.6-intel/egg/fontmake/font_project.py", line 159, in build_otfs
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.6-intel/egg/fontmake/font_project.py", line 210, in save_otfs
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/ufo2ft/__init__.py", line 30, in compileOTF
    postProcessor = OTFPostProcessor(otf, ufo)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/ufo2ft/otfPostProcessor.py", line 15, in __init__
    otf.save(stream)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 91, in compile
    return writer.getAllData()
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 412, in getAllData
    tableData = table.getData()
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 282, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 0, 'ItemName:', 'PairSet', 'ItemIndex:', 1)
Reaping losing child 0x7fabd2504a30 PID 75307 
make: *** [src/NotoSansEthiopic-MM.glyphs] Error 1
Removing child 0x7fabd2504a30 PID 75307 from chain.
Failed to remake target file `src/NotoSansEthiopic-MM.glyphs'.
marekj-macbookpro3:noto-source marekj$

**Comment by marekjez86** [comment]
This one was using my Mac the other #139 one was running on my Linux.

**Comment by marekjez86** [comment]
unable to reproduce. right now I can build src/NotoSansSymbols2-Regular.glyphs
appears to be fixed
