### ISSUE TITLE
traceback while building  src/NotoSansSymbols2-Regular.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#147]
just appeared as of 2016-09-17 (src/NotoSansSymbols2-Regular.glyphs can be found on github in noto-source/src/NotoSansSymbols2-Regular.glyphs )

```
==== building src/NotoSansSymbols2-Regular.glyphs ====
cffCompressor: cffCompressor.cc:297: void charstring_pool_t::writeEncoding(const encoding_list&, const std::map<const subs
tring_t*, unsigned int>&, std::ostream&): Assertion `enc.size() < 128' failed.
>> Checking Glyphs source for illegal glyph names
>> Building UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
>>> Writing master_ufo/NotoSansSymbols2-Regular.ufo
>>> Building instances

>> Building OTFs
>> Decomposing glyphs for NotoSansSymbols2-Regular
>> Removing overlaps for NotoSansSymbols2-Regular
>> Saving OTF for NotoSansSymbols2-Regular
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapp
er
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 31, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/otfPostProcessor.py", line 25, in process
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 115, in compress
    self.run_executable()
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 135, in run_executa
ble
    cxxCompressor.compreff(self.font, use_lib=False, **self.options)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 248, in compre
ff
    subrs, glyph_encodings = read_data(td, results)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 148, in read_d
ata
    enc, num_read = get_encoding(results[pos:], subrs)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 110, in get_en
coding
    num_calls = data_buffer[pos]
IndexError: array index out of range
```

**Comment by jamesgk** [comment]
Should be fixed by https://github.com/googlei18n/noto-source/commit/571bec880555327cd735c6df15853d8f3348c009.

**Comment by marekjez86** [comment]
verified as fixed
