### ISSUE TITLE
AssertionError: ((34, [38, 34, 37, 38, 38, 37, 38, 38]), 'list', '.PairSet', 'PairPos', 'list', '.SubTable', 'Lookup', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#165]
while building src/NotoSansDevanagari/NotoSansDevanagari-MM.plist

Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 0.61, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0},
 {'custom': 0, 'weight': -1.0, 'width': -1.0},
 {'custom': 0, 'weight': 0, 'width': -1.0},
 {'custom': 0, 'weight': 0.61, 'width': -1.0},
 {'custom': 0, 'weight': 1.0, 'width': -1.0}]
Building variations tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/__main__.py", line 111, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 327, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 368, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 417, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 164, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 248, in save_otfs
    interpolate_layout_from, loc, finder)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/interpolate_layout.py", line 102, in interpolate_layout
    merge_tables(font, merger, master_fonts, axes, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in merge_tables
    merger.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 46, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 46, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 44, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((34, [38, 34, 37, 38, 38, 37, 38, 38]), 'list', '.PairSet', 'PairPos', 'list', '.SubTable', 'Lookup', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
make: *** [src/NotoSansDevanagari/NotoSansDevanagari-MM.plist] Error 1

**Comment by marekjez86** [comment]
unable to reproduce as of 25/Oct/2016
