### ISSUE TITLE
puzzled by error while ==== building src/NotoSansDisplayRoman-MM.glyphs ====

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#170]
building https://github.com/googlei18n/noto-source/blob/master/src/NotoSansDisplayRoman-MM.glyphs

I get ....

INFO:mutatorMath:Writing NotoSansDisplay-SemiCondensedBlack.ufo to master_ufo/../instance_ufo/NotoSansDisplay-SemiCondensedBlack.ufo
INFO:mutatorMath:../instance_ufo/NotoSansDisplay-SemiCondensedBlack.ufo:

and 

INFO:fontmake:Removing overlaps for NotoSansDisplay-SemiCondensedThin
ERROR:fontmake:FaileROR:fontmake:Failed to remove overlaps for NotoSansUI-SemiCondensedThin: 'uniA767'
Found 10 glyph names containing hyphens: LL-middleWelsh, V-middleWelsh, dasiapneumatacomb-cy, ll-middleWelsh, mediumspace-math, ...

This leads to traceback
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/**main**.py", line 111, in main
    project.run_from_glyphs(glyphs_path, *_args)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 327, in run_from_glyphs
    designspace_path, instance_data=instance_data, *_kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 368, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, *_kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 417, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, *_kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 163, in build_otfs
    self.remove_overlaps(ufos)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(_args, *_kwds)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 107, in remove_overlaps
    union(contours, glyph.getPointPen())
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 100, in union
    return _performOperation("union", contours, [], outPen)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 66, in _performOperation
    operation, subjectFillType="nonZero", clipFillType="nonZero")
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 41, in clipExecute
    raise InvalidSubjectContourError("contour %d is invalid for clipping" % i)
booleanOperations.exceptions.InvalidSubjectContourError: contour 0 is invalid for clipping

I do not understand why. I cannot see anything obvious in the glyph under Glyphs.app

![unia767](https://cloud.githubusercontent.com/assets/13322623/19707503/c549c66c-9acc-11e6-9ac1-9370cba68060.jpg)

same error happens ERROR:fontmake:Failed to remove overlaps for NotoSansUI-SemiCondensedThin: 'uniA767'

**Comment by anthrotype** [comment]
@marekjez86 the problematic contour is not in the .glyphs file but in the generated `instance_ufo/NotoSansDisplay-SemiCondensedBlack.ufo`.

<img width="243" alt="screenshot 2016-10-26 10 50 37" src="https://cloud.githubusercontent.com/assets/6939968/19721427/139d49fe-9b6a-11e6-8bc2-da5abcdffddf.png">

it's the same as #161, a contour that's flattened to a line after interpolation.

**Comment by marekjez86** [comment]
@anthrotype  : thank you.
Assigning to @behdad  to investigate fixing it

**Comment by marekjez86** [comment]
I think I fixed it in the source. I do not think it's relevant any longer (unless you want to deal with it in the code). I also filed the following bugs against the source provider: https://github.com/googlei18n/noto-fonts/issues/787 and https://github.com/googlei18n/noto-fonts/issues/785
