### ISSUE TITLE
cannot build 4 fonts: NotoSansKhmer, NotoSansMyanmar, NotoSansMyanmarUI and NotoSerifMyanmar

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#178]
cannot build 4 fonts: NotoSansKhmer, NotoSansMyanmar, NotoSansMyanmarUI and NotoSerifMyanmar

I'll check if this could be a source error

NotoSansKhmer, NotoSansMyanmar, NotoSansMyanmarUI and NotoSerifMyanmar crash with the same stack trace but different values of AssertionError

the stack trace below is for NotoSerifMyanmar

```
Replacing all hyphens with periods.
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
>>> Writing master_ufo/NotoSerifMyanmar-Light.ufo
>>> Writing master_ufo/NotoSerifMyanmar-Regular.ufo
>>> Writing master_ufo/NotoSerifMyanmar-Bold.ufo
>>> Writing master_ufo/NotoSerifMyanmar-CondensedLight.ufo
>>> Writing master_ufo/NotoSerifMyanmar-Condensed.ufo
>>> Writing master_ufo/NotoSerifMyanmar-CondensedBold.ufo
Index of base master: 1
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (28.0, 128.0, 194.0),
 'width': (70.0, 100.0, 100.0)}
Location: {'width': 100.0, 'weight': 28.0, 'custom': 100.0}
Master locations:
[{'custom': 100.0, 'weight': 28.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 128.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 194.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 28.0, 'width': 70.0},
 {'custom': 100.0, 'weight': 128.0, 'width': 70.0},
 {'custom': 100.0, 'weight': 194.0, 'width': 70.0}]
Normalized location: {'width': 0, 'weight': -1.0, 'custom': 0}
Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0},
 {'custom': 0, 'weight': -1.0, 'width': -1.0},
 {'custom': 0, 'weight': 0, 'width': -1.0},
 {'custom': 0, 'weight': 1.0, 'width': -1.0}]
Building variations tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/__main__.py", line 111, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 328, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 371, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 420, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 165, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 249, in save_otfs
    interpolate_layout_from, loc, finder)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/interpolate_layout.py", line 311, in interpolate_layout
    merge_tables(font, merger, master_fonts, axes, base_idx, ['GPOS'])
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 83, in merge_tables
    merger.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 70, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 51, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 70, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 51, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 70, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 51, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 72, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 60, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 70, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 51, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 70, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 51, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.0-py2.7.egg/fontTools/varLib/merger.py", line 74, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((1, [2, 1, 2, 2, 2, 2]), 'int', '.LookupCount', 'Feature', '.Feature', 'FeatureRecord', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')

=====================

NotoSansKhmer
AssertionError: ((35, (44, 35, 43, 44, 44, 47)), 'int', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
=====================
NotoSansMyanmar
AssertionError: ((28, (28, 28, 36, 36, 28, 29, 36, 36)), 'int', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
=====================
NotoSansMyanmarUI
AssertionError: ((28, (27, 28, 36, 36, 28, 29, 37, 36)), 'int', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
```

**Comment by behdad** [comment]
@punchcutter and I talked about this.  Will continue today.

**Comment by marekjez86** [comment]
@behdad + @jamesgk : what would cause this type of problems? would problematic interpolation paths be an issue? I looked at NotoSansKhmer and Light starting points are very different from the rest in many many glyphs.

**Comment by marekjez86** [comment]
duplicate of https://github.com/googlei18n/fontmake/issues/171
