### ISSUE TITLE
FeatureLibError: Expected a glyph class with 1 elements after "by", but found a glyph class with 2 elements

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#185]
building fonts using gNotoSansBatak.glyphs as input
[gNotoSansBatak.zip](https://github.com/googlei18n/fontmake/files/584172/gNotoSansBatak.zip)

gNotoSansBatak.glyphs was created by opening https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansBatak-Regular.ttf  in Glyphs.app and saving it as a glyphs file

UFO is here [NotoSansBatak-Regular.zip](https://github.com/googlei18n/fontmake/files/584182/NotoSansBatak-Regular.zip)

I either need to fix the source or FeatureLib needs to learn to accept it :-)

Please advise

========= gNotoSansBatak.glyphs ===========
bash build.sh build_one src/gNotoSansBatak.glyphs
INFO:fontmake:Checking Glyphs source for illegal glyph names
INFO:fontmake:Building master UFOs and designspace from Glyphs source
INFO:fontmake:Interpolating master UFOs from designspace
INFO:mutatorMath:Executing designspace document: master_ufo/NotoSansBatak-Regular.designspace
INFO:mutatorMath:Writing NotoSansBatak-Regular.ufo to master_ufo/../instance_ufo/NotoSansBatak-Regular.ufo
INFO:mutatorMath:../instance_ufo/NotoSansBatak-Regular.ufo:
Possibly missing unicodes for 1 glyphs: 
        batak_null
INFO:mutatorMath:Done
INFO:fontmake:Building OTFs
INFO:fontmake:Decomposing glyphs for NotoSansBatak-Regular
INFO:fontmake:Removing overlaps for NotoSansBatak-Regular
INFO:fontmake:Saving OTF for NotoSansBatak-Regular
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
>>> Writing master_ufo/NotoSansBatak-Regular.ufo
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/__main__.py", line 111, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 347, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 390, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 439, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 165, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/rel/fontmake/Lib/fontmake/font_project.py", line 263, in save_otfs
    convertCubics=False, optimizeCff=subroutinize)
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 28, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 38, in compile
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 176, in setupFile_featureTables
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/builder.py", line 25, in addOpenTypeFeaturesFromS
tring
    addOpenTypeFeatures(font, featurefile)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/builder.py", line 78, in build
    self.parseTree = Parser(self.file).parse()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/parser.py", line 48, in parse
    statements.append(self.parse_feature_block_())
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/parser.py", line 1059, in parse_feature_block_
    self.parse_block_(block, vertical, stylisticset, size_feature)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/parser.py", line 1136, in parse_block_
    statements.append(self.parse_substitute_())
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+6.g2508350-py2.7.egg/fontTools/feaLib/parser.py", line 619, in parse_substitute_
    (len(glyphs), len(replacements)), location)
fontTools.feaLib.error.FeatureLibError: instance_ufo/NotoSansBatak-Regular.ufo/features.fea:6:1: Expected a glyph class with 1 elements after "by", but found a glyph class with 2 elements
make: *** [src/gNotoSansBatak.glyphs] Error 1

**Comment by marekjez86** [comment]
note that gNotoSansBatak.glyphs has the following ccmp features which might be incorrectly imported by the Glyphs.app ... I'm primary interested in getting gNotoSansBatak.glyphs compiled so if somebody could help me to correct this into a proper but equivalent features I'd appreciate it.

sub uni1BC0 uni1BE7 uni1BC0 uni1BF2' by  [uni1BE7 uni1BF2 ];
sub uni1BC0 uni1BE8 uni1BC0 uni1BF2' by  [uni1BE8 uni1BF2 ];
sub uni1BC0 uni1BE9 uni1BC0 uni1BF2' by  [uni1BE9 uni1BF2 ];
sub uni1BC0 uni1BEA uni1BC0 uni1BF2' by  [uni1BEA uni1BF2 ];
sub uni1BC0 uni1BEB uni1BC0 uni1BF2' by  [uni1BEB uni1BF2 ];
sub uni1BC0 uni1BEC uni1BC0 uni1BF2' by  [uni1BEC uni1BF2 ];
sub uni1BC0 uni1BED uni1BC0 uni1BF2' by  [uni1BED uni1BF2 ];
sub uni1BC0 uni1BEF uni1BC0 uni1BF2' by  [uni1BEF uni1BF2 ];
sub uni1BC0 uni1BEE uni1BC0 uni1BF2' by  [uni1BEE uni1BF2 ];
sub uni1BE7' uni1BC0 uni1BE7 uni1BF2 by batak_null ;
sub uni1BE8' uni1BC0 uni1BE8 uni1BF2 by batak_null ;
sub uni1BE9' uni1BC0 uni1BE9 uni1BF2 by batak_null ;
sub uni1BEA' uni1BC0 uni1BEA uni1BF2 by batak_null ;
sub uni1BEB' uni1BC0 uni1BEB uni1BF2 by batak_null ;
sub uni1BEC' uni1BC0 uni1BEC uni1BF2 by batak_null ;
sub uni1BEE' uni1BC0 uni1BEE uni1BF2 by batak_null ;
sub uni1BEF' uni1BC0 uni1BEF uni1BF2 by batak_null ;
sub uni1BED' uni1BC0 uni1BED uni1BF2 by batak_null ;

**Comment by marekjez86** [comment]
https://github.com/googlei18n/fontmake/issues/191 has more cases. closing this one.

**Comment by twardoch** [comment]
I've decompiled the features found in [NotoSansBatak-Regular.ttf](https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansBatak-Regular.ttf) into FEA using three apps: FontForge, DTL OTMaster and FontLab VI Public Preview. Attached in a ZIP here: [NotoSansBatak-Regular-fea.zip](https://github.com/googlei18n/fontmake/files/622336/NotoSansBatak-Regular-fea.zip)
