### ISSUE TITLE
fontTools/ttLib/sfnt.py issue while merging GPOS for Noto variation fonts

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#193]
I ran this command $fontmake -g src/NotoSansSymbols-MM.glyphs -o variable, and got the following error message:

...
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (26.0, 90.0, 190.0),
 'width': (100.0, 100.0, 100.0)}
Master locations:
[{'custom': 100.0, 'weight': 26.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 90.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 190.0, 'width': 100.0}]
Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0}]
Building variations tables
Generating gvar
/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py:171: UserWarning: glyph uni2318 has incompatible masters; skipping
  warnings.warn("glyph %s has incompatible masters; skipping" % glyph)
Generating HVAR
Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 428, in run_from_ufos
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 435, in main
    gx, model, master_ttfs = build(designspace_filename, finder)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 420, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 315, in _merge_OTL
    merge_tables(font, merger, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 69, in merge_tables
    merger.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/__init__.py", line 412, in __getitem__
    data = self.reader[tag]
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
    entry = self.tables[Tag(tag)]
KeyError: 'GPOS'

I got the same error message when trying to build variation fonts for NotoSerifGeorgian and NotoSansJavanese
fontmake -g src/NotoSerifGeorgian-MM.glyphs -o variable
fontmake -g src/NotoSansJavanese.glyphs -o variable

**Comment by jamesgk** [comment]
I think this is a fontTools/varLib bug, where it's crashing if there's no GPOS to interpolate.

**Comment by jamesgk** [comment]
So I think this is fixed upstream, and you can build these by updating fontTools. But for the cleanest possible build environment, we should create a variable font make target. I'll work on that.
