### ISSUE TITLE
fontTools/varLib/models.py issue while building variable font of NotoSansUIMono

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#196]
I ran this command $fontmake -g src/NotoSansUIMono-MM.glyphs -o variable and got this error message:

...
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (26.0, 90.0, 175.0),
 'width': (80.0, 100.0, 100.0)}
Master locations:
[{'custom': 100.0, 'weight': 26.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 90.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 145.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 175.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 26.0, 'width': 80.0},
 {'custom': 100.0, 'weight': 84.0, 'width': 80.0},
 {'custom': 100.0, 'weight': 128.0, 'width': 80.0},
 {'custom': 100.0, 'weight': 153.0, 'width': 80.0}]
Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 0.6470588235294118, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0},
 {'custom': 0, 'weight': -1.0, 'width': -1.0},
 {'custom': 0, 'weight': -0.09375, 'width': -1.0},
 {'custom': 0, 'weight': 0.4470588235294118, 'width': -1.0},
 {'custom': 0, 'weight': 0.7411764705882353, 'width': -1.0}]
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 428, in run_from_ufos
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 435, in main
    gx, model, master_ttfs = build(designspace_filename, finder)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 413, in build
    model = models.VariationModel(master_locs)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/models.py", line 100, in __init__
    self.locations = sorted(locations, key=keyFunc)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/models.py", line 126, in key
    onPointAxes = [axis for axis,value in loc.items() if value in axisPoints[axis]]
KeyError: u'wdth'

**Comment by marekjez86** [comment]
src/NotoSansUIMono-MM.glyphs doesn't exist any longer. please use src/NotoSansMono-MM.glyphs
