### ISSUE TITLE
error while Saving TTF for NotoSansEthiopic-Light

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#197]
Command:
fontmake -g src/NotoSansEthiopic-MM.glyphs -o variable

Error message:
>> Saving TTF for NotoSansEthiopic-Light
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 423, in run_from_ufos
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 179, in build_interpolatable_ttfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 233, in save_otfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/ufo2ft/__init__.py", line 39, in compileTTF
    return compileOTF(ufo, outlineCompilerClass=outlineCompilerClass, **kwargs)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/ufo2ft/__init__.py", line 30, in compileOTF
    postProcessor = OTFPostProcessor(otf, ufo)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/ufo2ft/otfPostProcessor.py", line 15, in __init__
    otf.save(stream)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/__init__.py", line 652, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/__init__.py", line 663, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 91, in compile
    return writer.getAllData()
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 419, in getAllData
    tableData = table.getData()
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 289, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 0)

**Comment by marekjez86** [comment]
@xiangyexiao : Did you rebuild the fontmake? Does it still happen? It looks like an exact duplicate of https://github.com/googlei18n/fontmake/issues/143

**Comment by behdad** [comment]
> @xiangyexiao : Did you rebuild the fontmake? Does it still happen? It looks like an exact duplicate of #143

That, and question I've asked million times before: why does NotoSansEhtiopic has such big kern table?
