### ISSUE TITLE
'Args to zip in cu2qu should have equal lengths' issue while building interpolation-compatible TTFs for NotoSansKhmer

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#198]
fontmake -g src/NotoSansKhmer/NotoSansKhmer-MM.glyphs --mti-source src/NotoSansKhmer/NotoSansKhmer-MM.plist -o variable

>> Building interpolation-compatible TTFs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 423, in run_from_ufos
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 178, in build_interpolatable_ttfs
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 138, in convert_curves
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 195, in fonts_to_quadratic
    _fonts_to_quadratic(fonts, max_errors, reverse_direction, stats)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 147, in _fonts_to_quadratic
    segments_by_location = zip(*[_get_segments(g) for g in glyphs])
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/cu2qu/ufo.py", line 47, in zip
    raise ValueError(msg + ' '.join(str(a) for a in args))
ValueError: Args to zip in cu2qu should have equal lengths: [('move', ((-397, 697),)), ('curve', ((-397, 697), (-380, 721), (-344, 750), (-311, 750))), ('curve', ((-311, 750), (-284, 750), (-262, 742), (-236, 700))), ('line', ((-180, 766),)), ('curve', ((-180, 766), (-213, 816), (-242, 829), (-292, 830))), ('curve', ((-292, 830), (-273, 856), (-250, 896), (-241, 926))), ('line', ((-316, 958),)), ('curve', ((-316, 958), (-334, 908), (-377, 848), (-448, 783))), ('close', ())] [('move', ((-201, 691),)), ('line', ((-154, 735),)), ('curve', ((-154, 735), (-189, 788), (-241, 810), (-298, 801))), ('curve', ((-298, 801), (-276, 837), (-261, 859), (-236, 919))), ('line', ((-285, 938),)), ('curve', ((-285, 938), (-301, 877), (-361, 808), (-443, 747))), ('line', ((-410, 695),)), ('curve', ((-410, 695), (-371, 732), (-339, 748), (-303, 748))), ('curve', ((-303, 748), (-266, 748), (-232, 737), (-201, 691))), ('close', ())] [('move', ((-204, 698),)), ('line', ((-183, 714),)), ('curve', ((-183, 714), (-221, 766), (-261, 794), (-328, 778))), ('curve', ((-328, 778), (-295, 824), (-279, 853), (-248, 912))), ('line', ((-272, 921),)), ('curve', ((-272, 921), (-300, 862), (-345, 787), (-411, 724))), ('line', ((-395, 704),)), ('curve', ((-395, 704), (-359, 737), (-336, 757), (-296, 757))), ('curve', ((-296, 757), (-253, 757), (-235, 742), (-204, 698))), ('close', ())] [('move', ((-219, 691),)), ('line', ((-181, 735),)), ('curve', ((-181, 735), (-212, 787), (-252, 806), (-299, 801))), ('curve', ((-299, 801), (-279, 837), (-265, 869), (-249, 919))), ('line', ((-290, 938),)), ('curve', ((-290, 938), (-307, 877), (-355, 810), (-422, 747))), ('line', ((-394, 695),)), ('curve', ((-394, 695), (-362, 730), (-335, 748), (-303, 748))), ('curve', ((-303, 748), (-273, 748), (-246, 737), (-219, 691))), ('close', ())] [('move', ((-408, 697),)), ('curve', ((-408, 697), (-377, 724), (-345, 750), (-304, 750))), ('curve', ((-304, 750), (-266, 750), (-244, 741), (-211, 700))), ('line', ((-144, 766),)), ('curve', ((-144, 766), (-181, 820), (-219, 833), (-279, 830))), ('curve', ((-279, 830), (-252, 867), (-235, 897), (-226, 927))), ('line', ((-307, 958),)), ('curve', ((-307, 958), (-329, 908), (-380, 848), (-466, 783))), ('close', ())] [('move', ((-201, 698),)), ('line', ((-180, 715),)), ('curve', ((-180, 715), (-222, 762), (-255, 791), (-333, 781))), ('curve', ((-333, 781), (-298, 825), (-282, 848), (-242, 911))), ('line', ((-267, 919),)), ('curve', ((-267, 919), (-307, 851), (-368, 774), (-425, 723))), ('line', ((-410, 702),)), ('curve', ((-410, 702), (-365, 742), (-346, 758), (-305, 758))), ('curve', ((-305, 758), (-259, 758), (-239, 742), (-201, 698))), ('close', ())]

**Comment by xiangyexiao** [comment]
found this issue has been fixed in NotoSansKhmer delivered on Nov 28
