### ISSUE TITLE
KeyError: u'NotoSansDevanagari-Light'

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#201]
When I build (using makefile in noto-source) the source in the attached zip I encounter 

KeyError: u'NotoSansDevanagari-Light'

Is this a problem with my setup, source or pipeline tool?

[NotoSansDevanagari.zip](https://github.com/googlei18n/fontmake/files/628322/NotoSansDevanagari.zip)

>>> Writing master_ufo/NotoSansDevanagari-Condensed.ufo
>>> Writing master_ufo/NotoSansDevanagari-CondensedSemiBold.ufo
>>> Writing master_ufo/NotoSansDevanagari-CondensedBold.ufo
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 111, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 348, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 391, in run_from_designspace
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 440, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 166, in build_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.2.1+2.g8620714-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  **File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 261, in save_otfs
KeyError: u'NotoSansDevanagari-Light'**
INFO:fontmake:Checking Glyphs source for illegal glyph names
INFO:fontmake:Building master UFOs and designspace from Glyphs source
INFO:fontmake:Interpolating master UFOs from designspace
INFO:mutatorMath:Executing designspace document: master_ufo/NotoSansDevanagari.designspace
INFO:mutatorMath:Writing NotoSansDevanagari-Thin.ufo to master_ufo/../instance_ufo/NotoSansDevanagari-Thin.ufo
INFO:mutatorMath:../instance_ufo/NotoSansDevanagari-Thin.ufo:

**Comment by jamesgk** [comment]
I can't reproduce this, so I'm guessing it's a setup error. I've just updated the setup target in noto-source to (finally) use a virtual environment so could you try again after another `make setup`?

**Comment by anthrotype** [comment]
👍 for using a virtual environment!

**Comment by marekjez86** [comment]
unable to reproduce it
