### ISSUE TITLE
shouldn't we be able to generate these type of variable fonts?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#204]
Input to fontmake: 
[gNotoSansBrahmi.glyphs.zip](https://github.com/googlei18n/fontmake/files/632572/gNotoSansBrahmi.glyphs.zip)

fontmake -g gNotoSansBrahmi.glyphs -o variable

generates the following log ending with KeyError: 'GPOS' (source has no GPOS; source was created by opening NotoSansBrahmi.TTF in glyphs.app and saving as gNotoSansBrahmi.glyphs; there was ONLY regular weight - should we be able to generate single weight variable fonts [i.e., really fonts where nothing will change]?)

============= src/gNotoSansBrahmi.glyphs ==============
INFO:fontmake:Checking Glyphs source for illegal glyph names
INFO:fontmake:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansBrahmi-Regular.ufo
INFO:fontmake:Building interpolation-compatible TTFs
INFO:fontmake:Converting curves compatibly
INFO:fontmake:Saving TTF for NotoSansBrahmi-Regular
INFO:fontmake:Building variable font master_ufo/NotoSansBrahmi-Regular-GX.ttf
New spline lengths:
1: 1114
2: 372
3: 5

Index of base master: 0
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (400.0, 400.0, 400.0),
 'width': (5.0, 5.0, 5.0)}
Master locations:
[{'custom': 100.0, 'weight': 400.0, 'width': 5.0}]
Normalized master locations:
[{'custom': 0, 'weight': 0, 'width': 0}]
Building variations tables
Generating gvar
Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 111, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 348, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 391, in run_from_designspace
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 461, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 209, in build_variable_font
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 422, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 316, in _merge_OTL
    merge_tables(font, merger, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 83, in merge_tables
    merger.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 414, in __getitem__
    data = self.reader[tag]
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
    entry = self.tables[Tag(tag)]
KeyError: 'GPOS'

**Comment by jamesgk** [comment]
Duplicate of https://github.com/googlei18n/fontmake/issues/193 I think.

**Comment by marekjez86** [comment]
Duplicate of https://github.com/googlei18n/fontmake/issues/193
