### ISSUE TITLE
AssertionError while building src/NotoSansMono-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#218]
for source see https://github.com/googlei18n/noto-source/blob/master/src/NotoSansMono-MM.glyphs

fontmake (or sub-system) problem? source problem?
```
============= src/NotoSansMono-MM.glyphs ==============
INFO:fontmake:Checking Glyphs source for illegal glyph names
INFO:fontmake:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansMono-CondensedBold.ufo
INFO:fontmake:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoSansMono.designspace
INFO:mutatorMath:	Generating instance NotoSansMono-Thin.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Light.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Regular.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Medium.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Bold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Black.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedThin.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensed.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedMedium.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedSemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-SemiCondensedBlack.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedThin.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-Condensed.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedMedium.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedSemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-CondensedBlack.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedThin.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedLight.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensed.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedMedium.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedSemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansMono-ExtraCondensedBlack.ufo
INFO:fontmake:Building OTFs
INFO:fontmake:Decomposing glyphs for NotoSansMono-Thin
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-Light
INFO:fontmake:Decomposing glyphs for NotoSansMono-Regular
INFO:fontmake:Decomposing glyphs for NotoSansMono-Medium
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-Bold
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-Black
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedThin
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedExtraLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensed
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedMedium
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedSemiBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedExtraBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-SemiCondensedBlack
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedThin
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedExtraLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-Condensed
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedMedium
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedSemiBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedExtraBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-CondensedBlack
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedThin
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedExtraLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedLight
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensed
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedMedium
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedSemiBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedExtraBold
INFO:fontmake:Decomposing glyphs for NotoSansMono-ExtraCondensedBlack
INFO:fontmake:Removing overlaps for NotoSansMono-Thin
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraLight
INFO:fontmake:Removing overlaps for NotoSansMono-Light
INFO:fontmake:Removing overlaps for NotoSansMono-Regular
INFO:fontmake:Removing overlaps for NotoSansMono-Medium
INFO:fontmake:Removing overlaps for NotoSansMono-SemiBold
INFO:fontmake:Removing overlaps for NotoSansMono-Bold
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraBold
INFO:fontmake:Removing overlaps for NotoSansMono-Black
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedThin
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedExtraLight
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedLight
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensed
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedMedium
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedSemiBold
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedBold
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedExtraBold
INFO:fontmake:Removing overlaps for NotoSansMono-SemiCondensedBlack
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedThin
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedExtraLight
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedLight
INFO:fontmake:Removing overlaps for NotoSansMono-Condensed
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedMedium
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedSemiBold
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedBold
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedExtraBold
INFO:fontmake:Removing overlaps for NotoSansMono-CondensedBlack
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedThin
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedExtraLight
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedLight
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensed
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedMedium
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedSemiBold
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedBold
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedExtraBold
INFO:fontmake:Removing overlaps for NotoSansMono-ExtraCondensedBlack
INFO:fontmake:Saving OTF for NotoSansMono-Thin
Found 10 glyph names containing hyphens: LL-middleWelsh, V-middleWelsh, dasiapneumatacomb-cy, ll-middleWelsh, mediumspace-math, ...
Replacing all hyphens with periods.
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/rel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 111, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 348, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 391, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 440, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 166, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 284, in save_otfs
    self.subset_otf_from_ufo(otf_path, ufo)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 325, in subset_otf_from_ufo
    subsetter.subset(font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2784, in subset
    self._prune_pre_subset(font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2611, in _prune_pre_subset
    table = font[tag]
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 420, in __getitem__
    table.decompile(data, self)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 49, in decompile
    self.table.decompile(reader, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 613, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 378, in read
    table.decompile(reader, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 609, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 110, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 378, in read
    table.decompile(reader, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 609, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 110, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 378, in read
    table.decompile(reader, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 613, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 378, in read
    table.decompile(reader, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 617, in decompile
    self.postRead(table, font)
  File "/usr/local/google/home/marekj/rel/noto-source/env/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 58, in postRead
    (r.StartCoverageIndex, len(glyphs))
AssertionError: (433, 426)
```

**Comment by jamesgk** [comment]
Looks similar to https://github.com/fonttools/fonttools/issues/719, but I'm not sure.

**Comment by jamesgk** [comment]
Actually, I'm not getting this error with the latest noto-source.

**Comment by marekjez86** [comment]
you are right, I cloned into a new tree and I cannot reproduce it.
