### ISSUE TITLE
56 source file compilations get now KeyError: 'Cc' (they didn't a couple of days ago)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#234]
Is this a newly caught source error?
56 source file compilations get now KeyError: 'Cc' (they didn't a couple of days ago)

for example, for https://github.com/googlei18n/noto-source/blob/master/src/gNotoSansLisu.glyphs

pipeline now produces 

============= src/gNotoSansLisu.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 368, in run_from_glyphs
    glyphs_path, family_name)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 93, in build_master_ufos
    family_name=family_name)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 91, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 70, in load_to_ufos
    family_name=family_name, debug=debug)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/builder.py", line 147, in to_ufos
    load_glyph(glyph, layer, glyph_data)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/builder.py", line 608, in load_glyph
    glyphinfo = glyphsLib.glyphdata.get_glyph(glyph.name)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/glyphdata.py", line 42, in get_glyph
    category, subCategory = _get_category(name, unistr, data)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/glyphsLib/glyphdata.py", line 76, in _get_category
    return data.DEFAULT_CATEGORIES[ucat]
KeyError: 'Cc'

**Comment by anthrotype** [comment]
It was a problem which occurred with so-called "narrow" Python 2.7 builds (built with UCS2 instead of UCS4), which is the norm for macOS and Windows python distributions; on Linux python is usually built with "wide" unicode support that's why the glyphsLib Travis CI did not catch this.

I believe I have fixed the issue with this commit, which is included in the latest v1.3.0 version of glyphsLib:
https://github.com/googlei18n/glyphsLib/commit/cc04e937109a40b627c79e80068f8be8dbe7eb1a

Please let me know if it still occurs after upgrading glyphsLib to v1.3.0.

**Comment by marekjez86** [comment]
@anthrotype : it is fixed. thank you

**Comment by anthrotype** [comment]
See https://github.com/googlei18n/glyphsLib/issues/103

**Comment by anthrotype** [comment]
this should now be fixed by https://github.com/googlei18n/glyphsLib/issues/105
