### ISSUE TITLE
source problem or code? same assert fails GX for NotoSansThai-MM.glyphs and NotoSansThaiUI-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#235]
We can now build src/NotoSerifThai-MM.glyphs

However we still cannot build https://github.com/googlei18n/noto-source/blob/master/src/NotoSansThai-MM.glyphs and https://github.com/googlei18n/noto-source/blob/master/src/NotoSansThaiUI-MM.glyphs

with exactly the same assertion

_AssertionError: ((13, [12, 13, 13, 11, 11, 11, 11, 11]), 'list', '.Class2Record', 'Class1Record', '[0]', 'list', '.Class1Record', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')_

Is this a source or something that we could handle?

Glyphs.app 2.4 can create and early version of var fonts for these (and doesn't issue any errors)

============= src/NotoSansThai-MM.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
WARNING:fontmake.font_project:Found 123 glyph names containing hyphens: angkhankhu-thai, boBaimai-thai, choChan-thai, choChang-thai, choChing-thai, ...
WARNING:fontmake.font_project:Replacing all hyphens with periods.
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThai-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 197
2: 745
3: 10

INFO:fontmake.font_project:Saving TTF for NotoSansThai-CondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSansThai-Condensed
INFO:fontmake.font_project:Saving TTF for NotoSansThai-CondensedSemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansThai-Bold
INFO:fontmake.font_project:Saving TTF for NotoSansThai-CondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSansThai-SemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansThai-Regular
INFO:fontmake.font_project:Saving TTF for NotoSansThai-Light
INFO:fontmake.font_project:Building variable font master_ufo/NotoSansThai-GX.ttf
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (26.0, 90.0, 190.0), 'width': (70.0, 100.0, 100.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 26.0, 'width': 100.0},
 {'weight': 90.0, 'width': 100.0},
 {'weight': 151.0, 'width': 100.0},
 {'weight': 190.0, 'width': 100.0},
 {'weight': 26.0, 'width': 70.0},
 {'weight': 90.0, 'width': 70.0},
 {'weight': 151.0, 'width': 70.0},
 {'weight': 190.0, 'width': 70.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0},
 {'weight': 0, 'width': 0},
 {'weight': 0.61, 'width': 0},
 {'weight': 1.0, 'width': 0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0, 'width': -1.0},
 {'weight': 0.61, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 104, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 404, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 281, in merge
    merger.mergeObjects(self, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((13, [12, 13, 13, 11, 11, 11, 11, 11]), 'list', '.Class2Record', 'Class1Record', '[0]', 'list', '.Class1Record', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
============= src/NotoSansThaiUI-MM.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
WARNING:fontmake.font_project:Found 123 glyph names containing hyphens: angkhankhu-thai, boBaimai-thai, choChan-thai, choChang-thai, choChing-thai, ...
WARNING:fontmake.font_project:Replacing all hyphens with periods.
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansThaiUI-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 194
2: 763
3: 10

INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-CondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-Light
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-Regular
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-SemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-CondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-CondensedSemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-Condensed
INFO:fontmake.font_project:Saving TTF for NotoSansThaiUI-Bold
INFO:fontmake.font_project:Building variable font master_ufo/NotoSansThaiUI-GX.ttf
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (26.0, 90.0, 190.0), 'width': (70.0, 100.0, 100.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 26.0, 'width': 100.0},
 {'weight': 90.0, 'width': 100.0},
 {'weight': 151.0, 'width': 100.0},
 {'weight': 190.0, 'width': 100.0},
 {'weight': 26.0, 'width': 70.0},
 {'weight': 90.0, 'width': 70.0},
 {'weight': 151.0, 'width': 70.0},
 {'weight': 190.0, 'width': 70.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0},
 {'weight': 0, 'width': 0},
 {'weight': 0.61, 'width': 0},
 {'weight': 1.0, 'width': 0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0, 'width': -1.0},
 {'weight': 0.61, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 104, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 404, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 281, in merge
    merger.mergeObjects(self, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((13, [12, 13, 13, 11, 11, 11, 11, 11]), 'list', '.Class2Record', 'Class1Record', '[0]', 'list', '.Class1Record', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by marekjez86** [comment]
I can build Thai fonts now. No longer an issue.
