### ISSUE TITLE
NotoSansCherokee-MM.glyphs GX build assertion

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#236]
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansCherokee-MM.glyphs

============= src/NotoSansCherokee-MM.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansCherokee-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansCherokee-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansCherokee-Bold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 240
2: 2289
3: 56
4: 8

INFO:fontmake.font_project:Saving TTF for NotoSansCherokee-Bold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansCherokee-Light
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansCherokee-Regular
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Building variable font master_ufo/NotoSansCherokee-GX.ttf
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (26.0, 90.0, 190.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 26.0}, {'weight': 90.0}, {'weight': 190.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0}, {'weight': 0}, {'weight': 1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 104, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 404, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 281, in merge
    merger.mergeObjects(self, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((18, [19, 18, 19]), 'int', '.Class1Count', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by marekjez86** [comment]
I can build Cherokee. No longer an issue.
