### ISSUE TITLE
NotoSerifArmenian-MM.glyphs and NotoSansArmenian-MM.glyphs GX build assertion

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#237]
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArmenian-MM.glyphs
https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifArmenian-MM.glyphs

============= src/NotoSansArmenian-MM.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
WARNING:glyphsLib.builder:Non-existent glyph class public.kern1.uni0574 found in kerning rules.
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSansArmenian-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 53
2: 656
3: 51
4: 4

INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-SemiBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-Light
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-Bold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-Condensed
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-CondensedBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-CondensedLight
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-Regular
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSansArmenian-CondensedSemiBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Building variable font master_ufo/NotoSansArmenian-GX.ttf
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (26.0, 90.0, 190.0), 'width': (70.0, 100.0, 100.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 26.0, 'width': 100.0},
 {'weight': 90.0, 'width': 100.0},
 {'weight': 151.0, 'width': 100.0},
 {'weight': 190.0, 'width': 100.0},
 {'weight': 26.0, 'width': 70.0},
 {'weight': 90.0, 'width': 70.0},
 {'weight': 151.0, 'width': 70.0},
 {'weight': 190.0, 'width': 70.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0},
 {'weight': 0, 'width': 0},
 {'weight': 0.61, 'width': 0},
 {'weight': 1.0, 'width': 0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0, 'width': -1.0},
 {'weight': 0.61, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 104, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 404, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 281, in merge
    merger.mergeObjects(self, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((33, [32, 33, 33, 33, 28, 28, 29, 28]), 'int', '.Class1Count', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

============= src/NotoSerifArmenian-MM.glyphs ==============
INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-SemiLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifArmenian-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 59
2: 835
3: 52
4: 8

INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-Light
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-CondensedSemiBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-SemiBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-Regular
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-CondensedLight
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-CondensedBold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-SemiLight
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-Bold
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Saving TTF for NotoSerifArmenian-Condensed
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
INFO:fontmake.font_project:Building variable font master_ufo/NotoSerifArmenian-GX.ttf
INFO:fontTools.varLib:Index of base master: 2
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (28.0, 94.0, 194.0), 'width': (70.0, 100.0, 100.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 28.0, 'width': 100.0},
 {'weight': 64.0, 'width': 100.0},
 {'weight': 94.0, 'width': 100.0},
 {'weight': 152.0, 'width': 100.0},
 {'weight': 194.0, 'width': 100.0},
 {'weight': 28.0, 'width': 70.0},
 {'weight': 94.0, 'width': 70.0},
 {'weight': 152.0, 'width': 70.0},
 {'weight': 194.0, 'width': 70.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0},
 {'weight': -0.45454545454545453, 'width': 0},
 {'weight': 0, 'width': 0},
 {'weight': 0.58, 'width': 0},
 {'weight': 1.0, 'width': 0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0, 'width': -1.0},
 {'weight': 0.58, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 169, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 104, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 404, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 88, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 281, in merge
    merger.mergeObjects(self, lst)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 67, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((19, [20, 20, 19, 13, 20, 15, 12, 12, 12]), 'int', '.Class1Count', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by marekjez86** [comment]
I can build Armenian fonts. This is no longer an issue.
