### ISSUE TITLE
GPOS merging error while building NotoSerifEthiopic-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#243]
building a new delivery https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifEthiopic-MM.glyphs

using
./build variable src/NotoSerifEthiopic-MM.glyphs
from noto-source

Is this a source issue or something in the pipeline?

INFO:fontmake.font_project:Checking Glyphs source for illegal glyph names
WARNING:fontmake.font_project:Found 555 glyph names containing hyphens: aGlottal-ethiopic, aPharyngeal-ethiopic, aaGlottal-ethiopic, aaPharyngeal-ethiopic, ba-ethiopic, ...
WARNING:fontmake.font_project:Replacing all hyphens with periods.
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifEthiopic-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 460
2: 2876
3: 180
4: 29

INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-CondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-Light
INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-Condensed
INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-Regular
INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-CondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSerifEthiopic-Bold
INFO:fontmake.font_project:Building variable font master_ufo/NotoSerifEthiopic-GX.ttf
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading TTF masters
INFO:fontTools.varLib:Axes:
{'weight': (28.0, 94.0, 194.0), 'width': (70.0, 100.0, 100.0)}
INFO:fontTools.varLib:Master locations:
[{'weight': 28.0, 'width': 100.0},
 {'weight': 94.0, 'width': 100.0},
 {'weight': 194.0, 'width': 100.0},
 {'weight': 28.0, 'width': 70.0},
 {'weight': 94.0, 'width': 70.0},
 {'weight': 194.0, 'width': 70.0}]
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0},
 {'weight': 0, 'width': 0},
 {'weight': 1.0, 'width': 0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/Users/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.1.1.dev0', 'console_scripts', 'fontmake')()
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontmake/__main__.py", line 171, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 370, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 413, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 483, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 217, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 346, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 243, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 106, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 79, in mergeLists
    self.mergeThings(value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 406, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 79, in mergeLists
    self.mergeThings(value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 90, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 283, in merge
    merger.mergeObjects(self, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 79, in mergeLists
    self.mergeThings(value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 69, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/marekj/newrel/noto-source/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 76, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((153, [152, 153, 153, 152, 153, 153]), 'list', '.Class2Record', 'Class1Record', '[0]', 'list', '.Class1Record', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by marekjez86** [comment]
I can build variable fonts now. No longer this is an issue.
