### ISSUE TITLE
Georgian: issue with source or with a parser? "AssertionError: illegal CharString" what does it mean?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#283]
source: https://github.com/googlei18n/noto-source/blob/master/src/NotoSansGeorgian-MM.glyphs
traceback:

INFO:fontmake.font_project:Removing overlaps for NotoSansGeorgian-ExtraCondensedBlack
INFO:fontmake.font_project:Saving OTF for NotoSansGeorgian-Thin
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.2.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 352, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 408, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 458, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 149, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 285, in save_otfs
    font.save(otf_path)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 123, in compile
    children = topCompiler.getChildren(strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 123, in compile
    children = topCompiler.getChildren(strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 431, in getChildren
    children.extend(topDict.getChildren(strings))
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 2043, in getChildren
    charStringsComp = CharStringsCompiler(items, strings, self)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 348, in __init__
    self.items = self.getItems(items, strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 507, in getItems
    cs.compile()
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/psCharStrings.py", line 1014, in compile
    self.check_program(program)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/psCharStrings.py", line 1007, in check_program
    "seac"), "illegal CharString"
AssertionError: illegal CharString

**Comment by marekjez86** [comment]
This is similar to https://github.com/googlei18n/fontmake/issues/190 (unreproducible)

I added print to before the assert. It fails/asserts on rlineto




NFO:fontmake.font_project:Saving OTF for NotoSerifGeorgian-Thin
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
endchar
callsubr
callsubr
callsubr
endchar
callsubr
callsubr
endchar
endchar
callsubr
callsubr
endchar
callsubr
callsubr
rlineto
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.2.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 352, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 408, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 458, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 149, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 285, in save_otfs
    font.save(otf_path)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 123, in compile
    children = topCompiler.getChildren(strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 431, in getChildren
    children.extend(topDict.getChildren(strings))
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 2043, in getChildren
    charStringsComp = CharStringsCompiler(items, strings, self)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 348, in __init__
    self.items = self.getItems(items, strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib.py", line 507, in getItems
    cs.compile()
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/psCharStrings.py", line 1015, in compile
    self.check_program(program)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/psCharStrings.py", line 1008, in check_program
    "seac"), "illegal CharString"
AssertionError: illegal CharString

**Comment by anthrotype** [comment]
I cannot produce.
I pulled the latest noto-source master, and run:

```sh
./build setup
./build src/NotoSansGeorgian-MM.glyphs
```

both the TTF and OTF built without errors, both with python 2.7.13 and 3.6.1 (on macOS).

**Comment by marekjez86** [comment]
I re-started my environment. Rebuilt the stuff and I cannot reproduce the issue.
