### ISSUE TITLE
 File "/usr/local/lib/python2.7/dist-packages/robofab/glifLib.py", line 297, in _getXMLTree raise KeyError, glyphName KeyError: 'uni000D' 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#29]
I built the pipeline in the evening (PDT) on 2016-02-16.

==== building src/NotoSerifArmenian-MM.glyphs  ====
[NotoSerifArmenian-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/133745/NotoSerifArmenian-MM.glyphs.zip)
WARNING: Non-existent glyph class @MMK_L_uni0533 found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni0532 found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni0535 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0553 found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni0539 found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni057C found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni0575 found in kerning rules.
WARNING: Non-existent glyph class @MMK_L_uni056A found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0584 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0575 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0553 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0562 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0573 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0565 found in kerning rules.
WARNING: Non-existent glyph class @MMK_R_uni0561 found in kerning rules.
[... many more ...]
WARNING: Non-existent glyph class @MMK_R_uni0575 found in kerning rules.
>> Checking Glyphs source for illegal glyph names
>> Loading master UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to RFonts
>>> Writing master_ufo/NotoSerifArmenian-Light.ufo
>>> Writing master_ufo/NotoSerifArmenian-SemiLight.ufo
>>> Writing master_ufo/NotoSerifArmenian-Regular.ufo
>>> Writing master_ufo/NotoSerifArmenian-SemiBold.ufo
>>> Writing master_ufo/NotoSerifArmenian-Bold.ufo
>>> Writing master_ufo/NotoSerifArmenianCondensed-Light.ufo
>>> Writing master_ufo/NotoSerifArmenianCondensed-Regular.ufo
>>> Writing master_ufo/NotoSerifArmenianCondensed-Bold.ufo
>> Removing overlaps for NotoSerifArmenian-Light
>> Removing overlaps for NotoSerifArmenian-SemiLight
>> Removing overlaps for NotoSerifArmenian-Regular
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 51, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 39, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 144, in run_from_glyphs
    self.run_from_ufos(ufos, is_instance=interpolate, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 159, in run_from_ufos
    self.remove_overlaps(ufo)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 80, in remove_overlaps
    for glyph in ufo:
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 696, in __iter__
    yield self.getGlyph(glyphName)
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsRF.py", line 556, in getGlyph
    n = self._loadGlyph(glyphName)
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsRF.py", line 213, in _loadGlyph
    self._glyphSet.readGlyph(glyphName=glyphName, glyphObject=g, pointPen=pen)
  File "/usr/local/lib/python2.7/dist-packages/robofab/glifLib.py", line 192, in readGlyph
    tree = self._getXMLTree(glyphName)
  File "/usr/local/lib/python2.7/dist-packages/robofab/glifLib.py", line 297, in _getXMLTree
    raise KeyError, glyphName
KeyError: 'uni000D'

**Comment by behdad** [comment]
Looks like another missing reference issue.

**Comment by marekjez86** [comment]
unable to reproduce it with the pipeline built on 2016-03-11
