### ISSUE TITLE
new fontmake behaviour: AssertionError while compiling src/NotoSansCarian-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#296]
source: https://github.com/googlei18n/noto-source/blob/master/src/NotoSansCarian-MM.glyphs

this is one of the fonts that has only Regular weight/width.

however, previous fontmake would build NotoSansCarian-Regular-VF.ttf

now it gets assertion error.

If this is an intended behaviour I'd like to know what needs to change in the sources to produce a font

fontmake -g src/NotoSansCarian-MM.glyphs -o variable
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansCarian-Regular.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 20
2: 144
3: 4

INFO:fontmake.font_project:Saving TTF for NotoSansCarian-Regular
INFO:fontmake.font_project:Building variable font variable_ttf/NotoSansCarian-Regular-VF.ttf
INFO:fontTools.varLib:Internal master locations:
[{}]
INFO:fontTools.varLib:Internal axis supports:
{}
INFO:fontTools.varLib:Normalized master locations:
[{}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.4.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 379, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 435, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 495, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 228, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/__init__.py", line 558, in build
    fvar,avar = _add_fvar_avar(vf, axes, instances)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/__init__.py", line 58, in _add_fvar_avar
    assert axes
AssertionError

**Comment by marekjez86** [comment]
Note that there are 17 other sources impacted by the above issue (in addition to the above mentioned NotoSansCarian-MM.glyphs)

**Comment by marekjez86** [comment]
There are 5 more sources with have *.plist files that generate this error, for a total of 1+17+5=23 files with this problem.

**Comment by brawer** [comment]
Well, if there’s just one single design master, it’s not possible to build a variable font because there’s nothing to interpolate. fontmake should probably detect this user error, and fail with a clear error message. (Of course, the tool could also be changed to silently build a “variable” font that has no variation axes; but it seems not very wise to let a compiler silently build something else than what was explicitly requested by the user).

**Comment by marekjez86** [comment]
I actually liked that it built me a font before. It indicated that this is a single width by naming it NotoSansCarian-Regular-VF.ttf

Now the process is:
- build all fonts
- see "assert axes" [the message should be better, more user friendly, e.g., "please re-run fontmake but remove the -o variable option for this source if you want to generate a font"]
- re-run fontmake for this source -o variable option

When I build 100 fonts I don't want to spend time looking for sources that build variable/do not build variable fonts. I just want fonts :-)
Alternatively provide "please re-run fontmake but remove the -o variable option for this source" but also allow me to --force-variable which would allow for the previous behaviour

**Comment by anthrotype** [comment]
As Sascha said, there's nothing to interpolate if the source only contains one master. If users asks for `-o variable`, we can't give them one so we should fail early, with a nice error message.

**Comment by brawer** [comment]
@marekjez86, do you know how come these alleged -MM fonts have just one single master? Don’t we plan to ship Noto (all of it) as a variable font?

**Comment by marekjez86** [comment]
@brawer : these were originally contracted out as a single master (Regular) fonts. we do not have funds to create Bold (or any other weight, width), so they'll remain as such unless someone else decides to add a different weight.

**Comment by davelab6** [comment]
I believe because they are used by such small language communities that
funding their expansion as Variable families was postponed or to be
crowdsourced.
