### ISSUE TITLE
Crash building Arima_Madurai_03.glyphs

### ISSUE THREAD

**Issue by davelab6** [googlei18n/fontmake#31]
```
mkdir -p ~/src/github.com/NDSICOVER/;
cd !$;
git clone https://github.com:NDSICOVER/Arima-Font;
cd Arima-Font/sources;
fontmake -g Arima_Madurai_03.glyphs;
>> Checking Glyphs source for illegal glyph names
Found 114 glyph names containing hyphens: a-tamil, aa-tamil, aaMatra-tamil, ai-tamil, aiMatra-tamil, ...
Replacing all hyphens with underscores.
>> Loading master UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to RFonts
>>> Writing master_ufo/ArimaMadurai-Light.ufo
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/Users/dcrossland/src/github.com/googlei18n/fontmake/Lib/fontmake/__main__.py", line 39, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/dcrossland/src/github.com/googlei18n/fontmake/Lib/fontmake/font_project.py", line 139, in run_from_glyphs
    ufos = self.build_masters(glyphs_path, is_italic)
  File "/Users/dcrossland/src/github.com/googlei18n/fontmake/Lib/fontmake/font_project.py", line 68, in build_masters
    return build_masters(glyphs_path, master_dir, is_italic)
  File "/usr/local/lib/python2.7/site-packages/glyphs2ufo/glyphslib.py", line 88, in build_masters
    write(ufo, master_dir)
  File "/usr/local/lib/python2.7/site-packages/glyphs2ufo/glyphslib.py", line 79, in write
    ufo.save(out_path)
  File "/usr/local/lib/python2.7/site-packages/robofab/objects/objectsRF.py", line 468, in save
    glyph._saveToGlyphSet(glyphSet, glyphName=glyphName, force=saveAs)
  File "/usr/local/lib/python2.7/site-packages/robofab/objects/objectsBase.py", line 1475, in _saveToGlyphSet
    glyphSet.writeGlyph(glyphName, self, self.drawPoints)
  File "/usr/local/lib/python2.7/site-packages/robofab/glifLib.py", line 214, in writeGlyph
    data = writeGlyphToString(glyphName, glyphObject, drawPointsFunc)
  File "/usr/local/lib/python2.7/site-packages/robofab/glifLib.py", line 411, in writeGlyphToString
    plistWriter.writeValue(lib)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 255, in writeValue
    self.writeDict(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 284, in writeDict
    self.writeValue(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 261, in writeValue
    self.writeArray(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 290, in writeArray
    self.writeValue(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 255, in writeValue
    self.writeDict(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 284, in writeDict
    self.writeValue(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 242, in writeValue
    self.simpleElement("string", value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 175, in simpleElement
    value = _escapeAndEncode(value)
  File "/usr/local/lib/python2.7/site-packages/robofab/plistlib.py", line 225, in _escapeAndEncode
    return text.encode("utf-8")             # encode as UTF-8
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by jamesgk** [comment]
This is due to non-ascii characters (e.g. á) in glyph annotations crashing the robofab-bundled plistlib. Maybe using the python library plistlib in robofab would fix this, not sure. Using defcon instead of robofab might as well.

**Comment by behdad** [comment]
plistlib in robofab definitely should go...  Can you send them a
pull-request for that at least?

So, where are we depending on robofab right now?

On Fri, Feb 19, 2016 at 3:36 AM, James Godfrey-Kittle <
notifications@github.com> wrote:

> This is due to non-ascii characters (e.g. á) in glyph annotations crashing
> the robofab-bundled plistlib. Maybe using the python library plistlib in
> robofab would fix this, not sure. Using defcon instead of robofab might as
> well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/31#issuecomment-185905638>.
>



-- 
behdad
http://behdad.org/

**Comment by adrientetar** [comment]
Too bad you're not using ufoLib, it's what we are maintaining these days.

**Comment by jamesgk** [comment]
> So, where are we depending on robofab right now?

We depend on robofab in glyphs2ufo and cu2qu, and possibly to an extent in ufo2ft (for ufoLib, maybe we can use the external one) and even booleanOperations (just for pens, it seems).

> Too bad you're not using ufoLib, it's what we are maintaining these days.

I don't think there's any reason why robofab couldn't use the external ufoLib itself, perhaps that could be in the same PR.

**Comment by jamesgk** [comment]
Actually, using python's plistlib yields this error as well. So maybe the only fix is to escape non-ascii characters before loading to UFO. Also, I tried taking ufoLib out of robofab, but its tests started failing. I guess they are slightly different somehow but I don't really want to spend a lot of time looking into this.

**Comment by adrientetar** [comment]
> in ufo2ft (for ufoLib, maybe we can use the external one) and even booleanOperations (just for pens, it seems).

I can confirm that these can work with just ufoLib.

**Comment by jamesgk** [comment]
> I can confirm that these can work with just ufoLib.

I just noticed that they even work without modification, that's great. I'm fine with removing the robofab import from ufo2ft entirely but I suppose it doesn't really matter.

>>Also, I tried taking ufoLib out of robofab

>https://github.com/unified-font-object/ufoLib

Yea, that's what I meant. I tried to use that instead, but some behavior seemed to have changed (just based on running tests) and I don't really want to dig into it (it's not important if we end up not using robofab anyways).
