### ISSUE TITLE
ValueError: The width should not be negative: 'fraction'

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/fontmake#317]
Trying to process `Cairo.glyphs` file from https://github.com/Gue3bara/Cairo with interpolation causes the following error:
```
$ fontmake -i -g sources/Cairo.glyphs 
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
WARNING:glyphsLib.builder:Non-existent glyph class public.kern1.d found in kerning rules.
WARNING:glyphsLib.builder:Non-existent glyph class public.kern1.i found in kerning rules.
WARNING:glyphsLib.builder:Non-existent glyph class public.kern1.l found in kerning rules.
INFO:glyphsLib.util:Writing master_ufo/Cairo-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/Cairo-Bold.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/Cairo.designspace
INFO:mutatorMath:	Generating instance Cairo-ExtraLight.ufo
INFO:mutatorMath:../instance_ufo/Cairo-ExtraLight.ufo:
Errors calculating 1 glyphs: 
	dcroat
INFO:mutatorMath:	Generating instance Cairo-Light.ufo
INFO:mutatorMath:../instance_ufo/Cairo-Light.ufo:
Errors calculating 1 glyphs: 
	dcroat
INFO:mutatorMath:	Generating instance Cairo-Regular.ufo
INFO:mutatorMath:	Generating instance Cairo-SemiBold.ufo
INFO:mutatorMath:../instance_ufo/Cairo-SemiBold.ufo:
Errors calculating 1 glyphs: 
	dcroat
INFO:mutatorMath:	Generating instance Cairo-Bold.ufo
INFO:mutatorMath:../instance_ufo/Cairo-Bold.ufo:
Errors calculating 1 glyphs: 
	dcroat
INFO:mutatorMath:	Generating instance Cairo-Black.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for Cairo-ExtraLight
INFO:fontmake.font_project:Decomposing glyphs for Cairo-Light
INFO:fontmake.font_project:Decomposing glyphs for Cairo-Regular
INFO:fontmake.font_project:Decomposing glyphs for Cairo-SemiBold
INFO:fontmake.font_project:Decomposing glyphs for Cairo-Bold
INFO:fontmake.font_project:Decomposing glyphs for Cairo-Black
INFO:fontmake.font_project:Removing overlaps for Cairo-ExtraLight
INFO:fontmake.font_project:Removing overlaps for Cairo-Light
INFO:fontmake.font_project:Removing overlaps for Cairo-Regular
INFO:fontmake.font_project:Removing overlaps for Cairo-SemiBold
INFO:fontmake.font_project:Removing overlaps for Cairo-Bold
INFO:fontmake.font_project:Removing overlaps for Cairo-Black
INFO:fontmake.font_project:Saving OTF for Cairo-ExtraLight
Traceback (most recent call last):
  File "/home/khaled/.local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/khaled/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/home/khaled/.local/lib/python3.6/site-packages/ufo2ft/__init__.py", line 37, in compileOTF
    otf = outlineCompiler.compile()
  File "/home/khaled/.local/lib/python3.6/site-packages/ufo2ft/outlineCompiler.py", line 86, in compile
    self.setupTable_hmtx()
  File "/home/khaled/.local/lib/python3.6/site-packages/ufo2ft/outlineCompiler.py", line 576, in setupTable_hmtx
    "The width should not be negative: '%s'" % (glyphName))
ValueError: The width should not be negative: 'fraction'
```

**Comment by moyogo** [comment]
'fraction' has width=0 in fontmaster Regular (weight=400) and width=10 in fontmaster Bold (weight=700). Extrapolating instances ExtraLight (weight=250) and Light (weight=300) will produce negative width. Glyphsapp zeroes out interpolated negative widths, ufo2ft doesn’t and raises ValueError.

ufo2ft could zero out negative widths and warn instead of raising ValueError.
The reason why we raise is because the user might have negative width thinking it is positive width (in a master for example). We can’t guess whether the intended value should be absolute or zeroed.

**Comment by behdad** [comment]
We don't actually extrapolate across one axis.  Are we sure we fully understand what's going on?

**Comment by anthrotype** [comment]
> We don't actually extrapolate across one axis.

it's true we don't. Maybe it was a float value that was almost 0, but on the negative end. That should be fixed by now (https://github.com/googlei18n/ufo2ft/pull/222).

I couldn't replicate the OP issue with the current fontmake and Cairo.glyphs. The fonts build successfully.

However I found another issue, unrelated to this, while attempting to compile the other source file from that repo, Cairo-italic.glyphs. I will open a separate issue for that.

I'll close this for now.
