### ISSUE TITLE
Ubuntu font: making fails

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#332]
1. Clone https://github.com/daltonmaag/ubuntu
2. `fontmake -u source/Ubuntu-R.ufo/`
```
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for Ubuntu-Bold
INFO:fontmake.font_project:Removing overlaps for Ubuntu-Bold
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 174, in build_otfs
    self.remove_overlaps(ufos)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 115, in remove_overlaps
    union(contours, glyph.getPointPen())
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/booleanOperationManager.py", line 104, in union
    return _performOperation("union", contours, [], outPen)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/booleanOperationManager.py", line 64, in _performOperation
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/booleanOperationManager.py", line 64, in <listcomp>
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/flatten.py", line 72, in __init__
    self.segments = _convertPointsToSegments(points)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/flatten.py", line 443, in _convertPointsToSegments
    willBeReversed=willBeReversed
  File "/home/nikolaus/.local/lib/python3.6/site-packages/booleanOperations/flatten.py", line 174, in __init__
    for pt1, pt2 in decomposeQuadraticSegment(pointCoordinates[1:]):
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/pens/basePen.py", line 360, in decomposeQuadraticSegment
    assert n > 0
AssertionError
```

Using `fontmake --keep-overlaps --no-production-names --keep-direction -o ttf -u source/Ubuntu-R.ufo/` works, but what causes the failure in the default configuration?

**Comment by anthrotype** [comment]
it's a known limitation of booleanOperations, which can't remove overlaps from UFO with quadratic contours. You need to use the `--keep-overlaps` option to skip booleanOperations.

**Comment by madig** [comment]
It would be nice to catch this and display an understandable error message, best with a reminder to `--keep-overlaps` :)
