### ISSUE TITLE
My build problem or fontmake? "AssertionError: Base master not found" compiling variable https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#339]
I rebuilt the fontmake, but now I get the following when compiling variable font from https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs (and all other sources where there are multiple weights; fonts with a single weight, for example https://github.com/googlei18n/noto-source/blob/master/src/NotoSansCuneiform-MM.glyphs , compile fine). Is this my build problem or fontmake?

Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.8.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 493, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 226, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/varLib/__init__.py", line 376, in build
    model = models.VariationModel(master_locs)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/varLib/models.py", line 136, in __init__
    keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=axisOrder)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/varLib/models.py", line 147, in getMasterLocationsSortKeyFunc
    assert {} in locations, "Base master not found."
AssertionError: Base master not found.

**Comment by anthrotype** [comment]
It's probably a setup issue on your side because it worked for me.
I pulled the latest noto-source and run `./build variable src/NotoSansArabic-MM.glyphs` and it compiled successfully.
How did you install fontmake?

**Comment by marekjez86** [comment]
appears to be a build error on my linux (my mac is fine)
