### ISSUE TITLE
Cannot pip3 install requirements

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#34]
Cannot install fontmake requirements with pip3. In python3, print statement need parentheses around their arguments.
```
$ sudo pip3 install -r requirements.txt
Downloading/unpacking git+https://github.com/behdad/fonttools.git (from -r requirements.txt (line 2))
  Cloning https://github.com/behdad/fonttools.git to /tmp/pip-o_bou4fc-build
  Running setup.py (path:/tmp/pip-o_bou4fc-build/setup.py) egg_info for package from git+https://github.com/behdad/fonttools.git
    
    warning: no files found matching 'LICENSE.txt'
    warning: no files found matching 'Doc/ChangeLog'
    warning: no files found matching 'Doc/*.txt'
    warning: no files found matching 'Doc/*.html'
    warning: no files found matching 'Windows/mcmillan.bat'
    warning: no files found matching 'Windows/ttx.ico'
    warning: no files found matching 'Windows/README.TXT'
    warning: no files found matching 'Windows/fonttools-win-setup.iss'
    warning: no files found matching 'Windows/fonttools-win-setup.txt'
Downloading/unpacking git+https://github.com/typesupply/feaTools.git (from -r requirements.txt (line 3))
  Cloning https://github.com/typesupply/feaTools.git to /tmp/pip-1xuyjbd4-build
  Running setup.py (path:/tmp/pip-1xuyjbd4-build/setup.py) egg_info for package from git+https://github.com/typesupply/feaTools.git
    
Downloading/unpacking git+https://github.com/googlei18n/cu2qu.git (from -r requirements.txt (line 9))
  Cloning https://github.com/googlei18n/cu2qu.git to /tmp/pip-e58ks7m8-build
  Running setup.py (path:/tmp/pip-e58ks7m8-build/setup.py) egg_info for package from git+https://github.com/googlei18n/cu2qu.git
    
Downloading/unpacking git+https://github.com/googlei18n/glyphs2ufo.git (from -r requirements.txt (line 10))
  Cloning https://github.com/googlei18n/glyphs2ufo.git to /tmp/pip-6zb84hi_-build
  Running setup.py (path:/tmp/pip-6zb84hi_-build/setup.py) egg_info for package from git+https://github.com/googlei18n/glyphs2ufo.git
    
Downloading/unpacking git+https://github.com/googlei18n/ufo2ft.git (from -r requirements.txt (line 11))
  Cloning https://github.com/googlei18n/ufo2ft.git to /tmp/pip-ltyotyv2-build
  Running setup.py (path:/tmp/pip-ltyotyv2-build/setup.py) egg_info for package from git+https://github.com/googlei18n/ufo2ft.git
    *** Warning: ufo2ft requires FontTools, see:
        fonttools.sf.net
    *** Warning: ufo2ft requires RoboFab, see:
        robofab.com
    
Downloading/unpacking git+https://github.com/robofab-developers/robofab.git (from -r requirements.txt (line 12))
  Cloning https://github.com/robofab-developers/robofab.git to /tmp/pip-_zdncxqh-build
  Running setup.py (path:/tmp/pip-_zdncxqh-build/setup.py) egg_info for package from git+https://github.com/robofab-developers/robofab.git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-_zdncxqh-build/setup.py", line 15
        print "*** Warning: FontTools needs the numpy library for some operations, see:"
                                                                                       ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-_zdncxqh-build/setup.py", line 15

    print "*** Warning: FontTools needs the numpy library for some operations, see:"

                                                                                   ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-_zdncxqh-build
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by adrientetar** [comment]
You can use my python3 repo: https://github.com/adrientetar/robofab/tree/python3

**Comment by jamesgk** [comment]
I was going to say this is another reason to use defcon, but then I noticed this: https://github.com/typesupply/defcon/blob/daeb4cd38d527a363e818e837fd2c1f1e9b16dad/setup.py#L12

Does defcon really depend on robofab (if not, should that code be removed)? Is defcon supposed to be python3-friendly?

**Comment by davelab6** [comment]
defcon needs robofab for ufoLib and pens only; ufoLib is split out now, but pens are yet to be split out?

**Comment by adrientetar** [comment]
I removed robofab dependency in my fork.

**Comment by jamesgk** [comment]
Can your changes be pushed upstream?

**Comment by adrientetar** [comment]
It's going to be some work but I'll get to it. That's the ufo3 branch though which is what I am maintaining these days.

**Comment by adrientetar** [comment]
It's going to be some work but I'll get to it. That's the ufo3 branch though which is what I am maintaining these days.

**Comment by behdad** [comment]
Filed https://github.com/googlei18n/fontmake/issues/38.

**Comment by jamesgk** [comment]
Robofab is no longer a dependency of fontmake.
