### ISSUE TITLE
My build problem or fontmake? "TypeError: compile() takes exactly 1 argument (2 given)" compiling static https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#340]
compiling static (i.e. non-variable) fonts from https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs
.... and all other ones generate the same error

Did I mess up build process on my linux box?

INFO:fontmake.font_project:Saving OTF for NotoSansArabic-Thin
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.8.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 44, in compileOTF
    postProcessor = PostProcessor(otf, ufo)
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/postProcessor.py", line 15, in __init__
    otf.save(stream)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib/__init__.py", line 135, in compile
    children = topCompiler.getChildren(strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib/__init__.py", line 438, in getChildren
    children.extend(topDict.getChildren(strings))
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib/__init__.py", line 2110, in getChildren
    items, strings, self, isCFF2=isCFF2)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib/__init__.py", line 355, in __init__
    self.items = self.getItems(items, strings)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/cffLib/__init__.py", line 522, in getItems
    cs.compile(self.isCFF2)
TypeError: compile() takes exactly 1 argument (2 given)

**Comment by anthrotype** [comment]
running `./build src/NotoSansArabic-MM.glyphs` from latest noto-source repo worked for me.
How did you install fontmake? What is the output of `pip list`?

**Comment by marekjez86** [comment]
appears to be a build error on my linux (my mac is fine)
