### ISSUE TITLE
Build of custom font fails with feature file syntax error while it works in Glyphs

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#347]
1. `wget https://github.com/madig/cantarell-fonts/raw/master/src/Cantarell.glyphs`
2. `fontmake -g Cantarell.glyphs -o otf`
```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/Cantarell-Regular.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-Regular
INFO:fontmake.font_project:Removing overlaps for Cantarell-Regular
INFO:fontmake.font_project:Saving OTF for Cantarell-Regular
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/ufo2ft/__init__.py", line 42, in compileOTF
    featureCompiler.compile()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/ufo2ft/featureCompiler.py", line 40, in compile
    self.setupFile_featureTables()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/ufo2ft/featureCompiler.py", line 145, in setupFile_featureTables
    filename=feapath)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/builder.py", line 25, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
    builder.build()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/builder.py", line 78, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/parser.py", line 53, in parse
    statements.append(self.parse_markClass_())
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/parser.py", line 500, in parse_markClass_
    self.expect_symbol_(";")
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/feaLib/parser.py", line 1330, in expect_symbol_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: /tmp/master_ufo/Cantarell-Regular.ufo/features.fea:124:1: Expected ';'
```

The same file exports without errors from Glyphs. I used #anchors in constructing e.g. `/n`, is it related to that?

**Comment by anthrotype** [comment]
Can you past here line 124 of your feature file?

Possibly related to https://github.com/adobe-type-tools/afdko/issues/191

**Comment by madig** [comment]
The file is only 117 lines long. The last table is (with a lot of base glyph names omitted):
```
table GDEF {
  # automatic
  GlyphClassDef
    [A ... numero], # Base
    [f_f f_f_i f_f_l fi fl _O.OE _horncomb.O _stem.d _stem.b _shoulder.n _stem.n
 _stem.g _stem.q _stem.p _stem.h _a.ae _A.AE _stem.thorn _N.Eng _k _stem.kgreenl
andic], # Liga
    [dieresiscomb dotaccentcomb gravecomb acutecomb hungarumlautcomb caroncomb.a
lt circumflexcomb caroncomb brevecomb ringcomb tildecomb macroncomb hookabovecom
b dblgravecomb breveinvertedcomb commaturnedabovecomb horncomb dotbelowcomb dier
esisbelowcomb commaaccentcomb cedillacomb ogonekcomb brevebelowcomb macronbelowc
omb strokeshortcomb strokelongcomb slashshortcomb slashlongcomb], # Mark
    ;
} GDEF
```

**Comment by madig** [comment]
(Probably better tracked over at fonttools).

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/issues/1100#issuecomment-343753440
