### ISSUE TITLE
UFO builds from lib.plist vs. contents.plist glyph lists

### ISSUE THREAD

**Issue by chrissimpkins** [googlei18n/fontmake#348]
#### Build platforms/application versions:
fontmake v1.3.0 from PyPI
OS: OS X 10.12 + Ubuntu Trusty (Travis builds for both platforms)
UFO source spec v2 files

#### Request

- Consider UFO to ttf builds (and probably otf too...) from glyph lists in contents.plist rather than lib.plist

#### Issue

During a lib.plist cleanup, I removed the public.glyphOrder key/values in our source files and this caused our UFO to ttf fontmake build to fail with the following exception (Linux build shown):

```
INFO:fontmake.font_project:Saving TTF for Hack-Regular
Traceback (most recent call last):
  File "/opt/python/2.7.13/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontmake/font_project.py", line 481, in run_from_ufos
    **kwargs)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontmake/font_project.py", line 193, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontmake/font_project.py", line 315, in save_otfs
    self.subset_otf_from_ufo(otf_path, ufo)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/fontmake/font_project.py", line 329, in subset_otf_from_ufo
    for glyph_name in ufo.lib[PUBLIC_PREFIX + 'glyphOrder']
KeyError: u'public.glyphOrder'
Unable to build the Hack-Regular variant set.  Build canceled.
make: *** [build-with-dependencies] Error 1
```

My understanding is that lib.plist is an optional file in the UFO spec, though it appears to be mandatory for fontmake builds from UFO source files.  I wanted to see if you might consider converting to contents.plist (mandatory file in UFO spec) for the glyph lists necessary for builds from UFO source.

The rationale for this request on our end is that we are struggling with how to manage the editor dependent lib.plist data that is unnecessary in the remote git repository (we are trying to support any UFO source editing tool). Ideally (for our purposes), everyone keeps their editor dependent data locally where they need it and builds occur from data in mandatory files that do not rely on the editor in use by the developer who commits.  If we can add lib.plist to our .gitignore file, it eliminates the need for review of thousands of lines of source when an author modifies something like the glyph list order based upon downstream developer / editor preferences.

**Comment by miguelsousa** [comment]
Keep in mind that if you rely on `contents.plist` alone you won't be able to control the font's glyph order. That might not be important to some people or workflows, but it surely is to others.

**Comment by chrissimpkins** [comment]
@miguelsousa Thanks Miguel.  Perhaps this is pointing to an issue with the spec itself if glyph order data are important to any build processes and *only* maintained in a file that is considered an optional part of the source spec (this is an assumption, is it stored elsewhere in UFO?).  This leads to circumstances where compilers use data that may or may not be present for the build leading to the problem above.

**Comment by anthrotype** [comment]
The lib.plist and public.glyphOrder may be optional for the UFO spec, however for this specific task of subsetting the generated font based on glyphs export flags it is actually needed, because in that `for` loop we are "zipping" the UFO's and the TTFont's glyph orders and iterating over the `old_name` (i.e. the glyph name in the UFO) and `new_name` (the name of that glyph in the TTFont after the uniXXXX names have been applied), so we are matching them by the respective order. 

If the UFO has no lib.plist and no public.glyphOrder, then ufo2ft will probably sort alphabetically (with the exception of .notdef that is always placed first, I think). But I don't like to rely on that.

**Comment by chrissimpkins** [comment]
@anthrotype Does this only apply when the subsetting flag is applied during the build or is there reliance on public.glyphOrder in lib.plist when you build the complete set as well?

**Comment by anthrotype** [comment]
yes, it's only needed when doing the subsetting, which is done automatically when a font has "com.schriftgestaltung.Keey Glyphs" list in the UFO lib.plist, or if any glyph contains a "com.schriftgestaltung.Glyphs.Export" set to False in its lib element.
You can disable this with `--no-subset` option.

**Comment by chrissimpkins** [comment]
Thank you!
