### ISSUE TITLE
source or fontmake error? NotoSansCuneiform-MM.glyphs causes ValueError

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#351]
Using https://github.com/googlei18n/noto-source/blob/master/src/NotoSansCuneiform-MM.glyphs as input to fontmake

============= src/NotoSansCuneiform-MM.glyphs ==============
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansCuneiform-Regular.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoSansCuneiform-Regular.designspace
INFO:mutatorMath:       Generating instance NotoSansCuneiform-Regular.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSansCuneiform-Regular
INFO:fontmake.font_project:Removing overlaps for NotoSansCuneiform-Regular
INFO:fontmake.font_project:Saving OTF for NotoSansCuneiform-Regular
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 183, i
n main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 37
8, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 43
4, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 47
3, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 17
5, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", l
ine 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 30
7, in save_otfs
    font.save(otf_path)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line
 221, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line
 657, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line
 660, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line
 671, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/ttLib/tables/C_F_F_.py",
 line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", lin
e 108, in compile
    topDict.recalcFontBBox()
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", lin
e 2325, in recalcFontBBox
    bounds = charString.calcBounds()
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", 
line 983, in calcBounds
    self.draw(boundsPen)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", 
line 978, in draw
    extractor.execute(self)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", 
line 301, in execute
    rv = handler(index)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", 
line 669, in op_hvcurveto
    args = self.vcurveto(args)
  File "/usr/local/google/home/marekj/newrel/fonttools/fonttools-venv/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", 
line 777, in vcurveto
    dya, dxb, dyb, dxc = args[:4]
ValueError: need more than 2 values to unpack

**Comment by anthrotype** [comment]
unable to repro.
I pulled the latest noto-source, did `./build setup` to ensure dependencies in the virtual environment are up to date, then run `./build src/NotoSansCuneiform-MM.glyphs`.
Both the TTF and OTF fonts were build successfully.

**Comment by marekjez86** [comment]
resolved
