### ISSUE TITLE
ValueError: Invalid value ('536') for attribute xHeight.

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#369]
When building:
```
fontmake -g NotoSansArabic-MM.glyphs -o ttf -i
```
I get:
```
...
INFO:mutatorMath:	Generating instance NotoSansArabic-SemiCondensedMedium.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-SemiCondensedSemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-SemiCondensedBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-SemiCondensedExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-SemiCondensedBlack.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedThin.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedLight.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensed.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedMedium.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedSemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSansArabic-ExtraCondensedBlack.ufo
Traceback (most recent call last):
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/.venv3/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/Lib/fontmake/__main__.py", line 186, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/Lib/fontmake/font_project.py", line 373, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/Lib/fontmake/font_project.py", line 423, in run_from_designspace
    ufos.extend(apply_instance_data(instance_data))
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/.venv3/src/glyphslib/Lib/glyphsLib/interpolation.py", line 380, in apply_instance_data
    set_custom_params(ufo, data=data)
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/.venv3/src/glyphslib/Lib/glyphsLib/builder/custom_params.py", line 141, in set_custom_params
    setattr(ufo.info, name, value)
  File "/usr/local/google/home/behdad/SSD/distillery/fontmake/.venv3/src/defcon/Lib/defcon/objects/info.py", line 38, in setter
    raise ValueError("Invalid value ({0}) for attribute {1}.".format(repr(value), name))
ValueError: Invalid value ('536') for attribute xHeight.
```

**Comment by anthrotype** [comment]
That is glyphsLib from git, not the last stable release, right?
I think it’s because there is no “xHeight” instance  custom parameter in Glyphs.app (it’s actually a property of a font master, not a custom parameter), but some of the Noto fonts still use it. User-defined custom parameters (unlike the built in ones) are all stored as strings because their type is unknown.
We need to fix the sources and remove that parameter.
Maybe also turn such errors into warnings..

**Comment by anthrotype** [comment]
fixed with https://github.com/googlei18n/glyphsLib/pull/270
