### ISSUE TITLE
Glyphs source from v2.5b breaks

### ISSUE THREAD

**Issue by MrBrezina** [googlei18n/fontmake#374]
This is what I get when I run `$ fontmake -g source.glyphs -o ufo -i` on a source which has been saved from the latest version of Glyphs.

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 81, in build_masters
    propagate_anchors=propagate_anchors)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 55, in load_to_ufos
    font = load(ifile)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 228, in load
    return loads(fp.read())
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 238, in loads
    data = p.parse(s)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 51, in parse
    result, i = self._parse(text, 0)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 95, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 137, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 152, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 101, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 179, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 95, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 137, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 152, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 101, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 179, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/parser.py", line 120, in _parse
    value = self.current_type(value)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by anthrotype** [comment]
Thanks David. We should make error messages from glyphsLib parser more meaningful to help debugging issues like this.
I’m away from laptop now, i’ll have a look later.
If you could install it in editable mode and put a try: except: around that line with a print(self.current_type, i), we could try to see what is the offending type and where it’s crashing.

**Comment by moyogo** [comment]
Some attribute names have slightly changed in 2.5b, from titlecase to
lowercase I believe. It should be simple to support both.

**Comment by MrBrezina** [comment]
Your commitment is admirable, amazing actually, but I don’t think anyone expects you to work on weekends!

**Comment by anthrotype** [comment]
> Some attribute names have slightly changed in 2.5b, from titlecase to lowercase

Could we please get a list of these? /cc @schriftgestalt

**Comment by schriftgestalt** [comment]
Can you give an example?

**Comment by anthrotype** [comment]
> Can you give an example?

I haven't checked yet as I don't have the source files. @moyogo suggested something may have changed in the latest beta, leading to the above mentioned crash in glyphsLib parser.

**Comment by moyogo** [comment]
After round-tripping GlyphsUnitTestSans.glyphs in 2.5b 1084 (https://github.com/moyogo/glyphslib/commit/9a07b1d5edfccc0916d37e0a11779687346e9315) I get the same error.

**Comment by anthrotype** [comment]
@moyogo could you try to insert print() or a debugger break point `import pdb; pdb.set_trace()` and get the value of self.current_type?

**Comment by MalcolmWooden** [comment]
Perhaps this is the same problem. I'm getting this error when trying one of our Glyphs files while others are made with no errors.

`INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 81, in build_masters
    propagate_anchors=propagate_anchors)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/__init__.py", line 59, in load_to_ufos
    propagate_anchors=propagate_anchors)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/builder/__init__.py", line 43, in to_ufos
    result = list(builder.masters)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/builder/builders.py", line 133, in masters
    self.to_ufo_glyph(ufo_glyph, layer, glyph)
  File "/usr/local/lib/python2.7/site-packages/glyphsLib/builder/glyph.py", line 40, in to_ufo_glyph
    ufo_glyph.lib[PUBLIC_PREFIX + 'markColor'] = GLYPHS_COLORS[color_index]
IndexError: tuple index out of range
`

**Comment by punchcutter** [comment]
@MalcolmWooden Your issue looks like the file came from FontLab with the Glyphs export script. That issue is open here: https://github.com/googlei18n/glyphsLib/issues/116 
I've seen that error before and just had to change or remove the colors in the font view in Glyphs. Then fontmake is fine.

**Comment by MalcolmWooden** [comment]
Thanks Punchcutter. The file has not been near FontLab but there has been some color changes in the font view glyph cells. I set them all back to "no color" and it now works!!

**Comment by anthrotype** [comment]
hey Malcolm! I'm glad you too are using fontmake :)
Zachary is working on a fix for those color tuples https://github.com/googlei18n/glyphsLib/pull/285

back to the point of this issue, did anyone figure out what are these allegedly new or renamed attributes in 2.5b that make the glyphsLib parser crash?

**Comment by anthrotype** [comment]
this should be fixed by glyphsLib 2.1.0, please confirm
https://github.com/googlei18n/glyphsLib/releases/tag/v2.1.0

**Comment by marekjez86** [comment]
@MrBrezina : is this still an issue?

**Comment by anthrotype** [comment]
nope
