### ISSUE TITLE
fontmake fails reading a .glyphs file

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#375]
1. Get https://github.com/madig/cantarell-fonts/raw/master/src/Cantarell.glyphs
2. `fontmake -g Cantarell.glyphs -o otf`
```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 81, in build_masters
    propagate_anchors=propagate_anchors)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 59, in load_to_ufos
    propagate_anchors=propagate_anchors)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/glyphsLib/builder/__init__.py", line 43, in to_ufos
    result = list(builder.masters)
  File "/home/nikolaus/.local/lib/python3.6/site-packages/glyphsLib/builder/builders.py", line 137, in masters
    ufo_font = self._ufos[layer_id]
KeyError: ''
```

**Comment by madig** [comment]
(Should this be filed in glyphsLib's issue tracker instead?)

**Comment by madig** [comment]
https://github.com/googlei18n/glyphsLib/issues/282
