### ISSUE TITLE
MarkCount / MarkArray

### ISSUE THREAD

**Issue by michielkauwatjoe** [googlei18n/fontmake#383]
I'm trying to generate a variable font with one axis from five weights. As far as I know the glyphs are compatible and the order is the same. However, I'm getting this AssertionError when fontmake tries to merge the GPOS table:

```
Building interpolation-compatible TTFs
Converting curves compatibly
New spline lengths: 1: 8, 2: 915, 3: 591, 4: 44, 5: 2
Saving TTF for Upgrade-UltraBlack
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Saving TTF for Upgrade-Hairline
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Saving TTF for Upgrade-Black
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Saving TTF for Upgrade-Light
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Attempting to fix OTLOffsetOverflowError %s
Saving TTF for Upgrade-Semibold
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Building variable font variable_ttf/UpgradeRoman-VF.ttf
Axes:
OrderedDict([('wght', {u'map': None, 'name': 'wght', 'default': 0.0, 'tag': 'wght', 'maximum': 500.0, 'minimum': 0.0, 'labelname': {'en': 'wght'}})])
Internal master locations:
[{'wght': 300.0},
 {'wght': 0.0},
 {'wght': 100.0},
 {'wght': 200.0},
 {'wght': 500.0}]
Internal axis supports:
{'wght': [0.0, 0.0, 500.0]}
Normalized master locations:
[{'wght': 0.6}, {'wght': 0.0}, {'wght': 0.2}, {'wght': 0.4}, {'wght': 1.0}]
Index of base master: 1
Building variable font
Loading master fonts
Generating fvar
Generating avar
No need for avar
Building variations tables
Generating MVAR
	xhgt: OS/2.sxHeight	[478, 462, 462, 470, 502]
Generating HVAR
font is <fontTools.ttLib.TTFont object at 0x124ecec50>
Merging OpenType Layout tables

Traceback (most recent call last):
  File "/Users/michiel/Code/TnBits/src/tnbits/toolparts/bakery/controller.py", line 240, in run
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 438, in run_from_designspace
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 497, in run_from_ufos
  File "/Users/michiel/Code/FontMake/Lib/fontmake/font_project.py", line 220, in build_variable_font
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/__init__.py", line 725, in build
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/__init__.py", line 518, in _merge_OTL
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 107, in mergeTables
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 94, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 71, in mergeObjects
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 94, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 71, in mergeObjects
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 94, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 71, in mergeObjects
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 96, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 81, in mergeLists
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 92, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 621, in merge
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 81, in mergeLists
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 94, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 71, in mergeObjects
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 94, in mergeThings
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 71, in mergeObjects
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/varLib/merger.py", line 98, in mergeThings
AssertionError: ((32, [32, 32, 34, 30, 18]), 'int', '.MarkCount', 'MarkArray', '.MarkArray', 'MarkBasePos', '[0]', 'Lookup', '[1]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```
Is something wrong with the source UFOs? How can I tell? This is in RoboFont 2 btw.

**Comment by khaledhosny** [comment]
Did you check your anchors? You might have glyphs with different anchors accross masters.

**Comment by michielkauwatjoe** [comment]
@khaledhosny They are different, so  that's probably it. Thank you, will close this for now.
