### ISSUE TITLE
KeyError: u'.notdef' with the newest pipeline (as of 9/Mar/2016 afternoon PST)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#40]
processing [Glyphs_Sapperlot.glyphs.zip](https://github.com/googlei18n/fontmake/files/166258/Glyphs_Sapperlot.glyphs.zip)

```
>> Saving TTF for GlyphsSapperlot-Regular
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 51, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 39, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 187, in run_from_glyphs
    kern_writer=GlyphsKernWriter, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 232, in run_from_ufos
    ufo, ttf=True, mti_feafiles=mti_paths.get(name), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 121, in save_otf
    otf.save(otf_path)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 645, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 645, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_g_l_y_f.py", line 81, in compile
    glyph = self.glyphs[glyphName]
KeyError: u'.notdef'
```

**Comment by marekjez86** [comment]
Note that previously I had https://github.com/googlei18n/fontmake/issues/28

This issue si gone.

**Comment by jamesgk** [comment]
This is definitely not a Glyphs file that the toolchain is accustomed to; the instance data doesn't seem to have weights but rather style variations.

**Comment by marekjez86** [comment]
OK. This came from https://github.com/DrTypo/sapperlot 
My Mac glyphs.app can export unhinted OTF files from Glyphs_Sapperlot.glyphs.

Treat at as possible enhancement request (just in case people will want to process the input files like this).

**Comment by adrientetar** [comment]
I think the specific issue here is essentially the same as #82, which is fixed.

**Comment by marekjez86** [comment]
This is fixed at this point. I'm closing the issue.
