### ISSUE TITLE
regression: compiling NotoSansDisplay-MM.glyphs now gives "ValueError: The width should not be negative: 'uniFEFF'"

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#400]
note that the last time NotoSans-MM.glyphs changed was on 14/Dec.
I was able to generate fonts on 16/Jan.
Since 16/Jan something in the pipeline changed and now I get:

compiling https://github.com/googlei18n/noto-source/blob/master/src/NotoSans-ItalicMM.glyphs generates now 

INFO:fontmake.font_project:Saving OTF for NotoSans-MediumItalic
INFO:fontmake.font_project:Saving OTF for NotoSans-SemiBoldItalic
INFO:fontmake.font_project:Saving OTF for NotoSans-BoldItalic
INFO:fontmake.font_project:Saving OTF for NotoSans-ExtraBoldItalic
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/release/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.4.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 186, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 369, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 437, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 476, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 169, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 286, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/__init__.py", line 62, in compileOTF
    otf = outlineCompiler.compile()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/outlineCompiler.py", line 85, in compile
    self.setupTable_hmtx()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/outlineCompiler.py", line 574, in setupTable_hmtx
    "The width should not be negative: '%s'" % (glyphName))
ValueError: The width should not be negative: 'uniFEFF'
I looked in the Glyphs.app and uniFEFF width is 0 in the sources (it is ZERO WIDTH NO-BREAK SPACE).

The same I get for NotoSansDisplay

INFO:fontmake.font_project:Saving OTF for NotoSansDisplay-ExtraLightItalic
INFO:fontmake.font_project:Saving OTF for NotoSansDisplay-LightItalic
INFO:fontmake.font_project:Saving OTF for NotoSansDisplay-Italic
INFO:fontmake.font_project:Saving OTF for NotoSansDisplay-MediumItalic
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/release/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.4.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 186, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 369, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 437, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 476, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 169, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 286, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/__init__.py", line 62, in compileOTF
    otf = outlineCompiler.compile()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/outlineCompiler.py", line 85, in compile
    self.setupTable_hmtx()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/ufo2ft/outlineCompiler.py", line 574, in setupTable_hmtx
    "The width should not be negative: '%s'" % (glyphName))
ValueError: The width should not be negative: 'uniFEFF'

Do we check if width <= 0 instead of width < 0 now?

**Comment by marekjez86** [comment]
Note that variable fonts are generated (have checked how good they are).

**Comment by behdad** [comment]
No, the code checks for "width < 0".

**Comment by anthrotype** [comment]
it looks like a font source issue to me. In the above mentioned fonts (NotoSans-ItalicMM.glyphs and NotoSansDisplay-ItalicMM.glyphs) the glyph "uniFEFF" (for the character "ZERO WIDTH NO-BREAK SPACE") does not have a 0 advance width for all the masters: some of the masters have a positive width (you can see that if you toggle between the different master layers with the top-right toolbar buttons). Somehow, after interpolating them, some instances end up with a negative width.

It should be fixed in the font sources by setting the width of uniFEFF glyph for all the masters to the value 0.

**Comment by marekjez86** [comment]
thanks for debugging it

**Comment by behdad** [comment]
> it looks like a font source issue to me. In the above mentioned fonts (NotoSans-ItalicMM.glyphs and NotoSansDisplay-ItalicMM.glyphs) the glyph "uniFEFF" (for the character "ZERO WIDTH NO-BREAK SPACE") does not have a 0 advance width for all the masters: some of the masters have a positive width (you can see that if you toggle between the different master layers with the top-left toolbar buttons). Somehow, after interpolating them, some instances end up with a negative width.

That sounds alarming though. Can you list the master / instance locations?

**Comment by anthrotype** [comment]
The test `width < 0` assumes integer values, but we now use floating points by default for all numeric values in interpolated UFO instances.
Since fontmake 1.4 we no longer set roundGeometry=True by default (unless --round-instances option is passed on the command line) when interpolating instances with MutatorMath (rounding actually occurs inside fontMath).
This is the commit that changed the default: https://github.com/googlei18n/fontmake/commit/d8baa40db65d599fc9eb9285e3b86353bd68f8b9

For example, in the "Noto Sans Display Medium Italic" instance, the uniFEFF glyph gets a float value for the advance width which is _almost_ zero: -8.526512829121202e-14

Instead of checking if width < 0, we should round it to integer first and then check. We round it anyway a few lines below that check because hmtx only accept integer advance widths.

**Comment by khaledhosny** [comment]
Apart of catching interpolation errors like this, is negative advance width really an error? `hmtx` does not allow it, but CFF seems to do (at least FontForge can write and read font with CFF table and negative advance width).

**Comment by anthrotype** [comment]
> is negative advance width really an error? 

for TrueType at least it is. For CFF, we do round it all the time... (at least, it takes a few less bytes ;)

**Comment by anthrotype** [comment]
opentype fonts should read width and height from hmtx and vmtx respectively, even for CFF flavored OpenType. Neither of these allow floats for the advance. So it should be rounded in both cases. In CFF2 it's gone.

**Comment by anthrotype** [comment]
and it's not an interpolation "error" but just the inevitable byproduct of floating point math

**Comment by anthrotype** [comment]
I just realised I conflated the two issues (width being a float and negative) into one, whereas Khaled was really talking about the second.

But anyway, the hmtx and vmtx should have priority over the width encoded in the CFF charstrings for OpenType fonts, and since the former tables require an _unsigned short integer_ it makes sense to always round the UFO glyph's width when encoding it in the OpenType font, and also it makes sense to raise an error in case it happens to be negative (which is most certainly an unwanted mistake).

**Comment by anthrotype** [comment]
and even if we were not checking width < 0, `struct` would raise a (less meaningful) error when attempting to pack a negative number into an unsigned short as it's out of range.

**Comment by khaledhosny** [comment]
Makes sense, thanks for elaboration.
