### ISSUE TITLE
Fatal: autohint causes a Traceback

### ISSUE THREAD

**Issue by typoman** [googlei18n/fontmake#407]
I used the following command on a ufo:
`fontmake -a -o ttf otf -u blahblah.ufo`

And got this traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 199, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 484, in run_from_ufos
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 187, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 311, in save_otfs
    ttfautohint(otf_path, hinted_otf_path, args=autohint)
  File "/usr/local/lib/python2.7/site-packages/fontmake/ttfautohint.py", line 32, in ttfautohint
    return subprocess.call(arg_list + args.split() + file_args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

Not sure what's happening. Looks like it's from ttfautohint.py. Can anyone else reproduce this on a UFO?

Thanks

**Comment by anthrotype** [comment]
Maybe you don’t have ttfautohint installed or it’s not in the PATH. Fontmake simply calls the external executable with those options.

**Comment by typoman** [comment]
I installed the ttfautohint using `pip install ttfautohint-py` and also `brew install ttfautohint --with-qt5` but same error occurred. `import ttfautohint` works in python too.

**Comment by typoman** [comment]
ok it's not the PATH, I will see how that goes.

**Comment by anthrotype** [comment]
Sorry ttfautohint-py is not hooked up to fontmake yet. The current fontmake expects the native ttfautohint binary to be in the PATH. You can brew install ttfautohint for now

**Comment by typoman** [comment]
Thanks, what made it work was downloading the ttfautohint binary from [freetype.sourceforge](http://freetype.sourceforge.net/ttfautohint/index.html) and adding it to the PATH by following command in terminal:

`export PATH=$PATH:path/to/the/folder/`

Now I don't get the Traceback. Thank you Cosimo!

**Comment by anthrotype** [comment]
the homebrewed ttfautohint should work too
