### ISSUE TITLE
<instance> attribute "filename" required?

### ISSUE THREAD

**Issue by justvanrossum** [googlei18n/fontmake#419]
Context: building a VF.

If I omit the `filename` attribute of an `<instance>` element in a designspace file I get an error. 

```
Traceback (most recent call last):
  File "buildVar.py", line 37, in <module>
    project.run_from_designspace(designspace_path=designspacePath, **args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontmake/font_project.py", line 437, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontmake/font_project.py", line 496, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontmake/font_project.py", line 210, in build_variable_font
    master_locations, _ = self._designspace_locations(designspace_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontmake/font_project.py", line 560, in _designspace_locations
    os.path.dirname(designspace_path), loc['filename']))
KeyError: 'filename'
```
Yet https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#attributes-8 says "filename: string. Required for MutatorMath. [...]"

From which I (perhaps incorrectly) understand it's not mandatory when building a VF. Which would be good, because the attribute makes no sense in that context.

**Comment by anthrotype** [comment]
Good point, I shall make that optional.
