### ISSUE TITLE
offset overflow error in MarkBasePos subtable when compiling some Noto fonts

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#450]
compiling https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifDisplay-ItalicMM.glyphs as a variable font (I generated both OTF and TTF fonts)

INFO:fontmake.font_project:Building variable font variable_ttf/NotoSerifDisplay-Italic-VF.ttf
INFO:fontTools.varLib:Axes:
OrderedDict([('Weight', {'map': {400.0: 94.0, 600.0: 152.0, 700.0: 194.0, 300.0: 28.0}, 'name': 'Weight', 'default': 400.0, 'tag': 'wght', 'maximum': 700.0, 'minimum': 300.0, u'labelname': {u'en': 'Weight'}}), ('Width', {u'map': None, 'name': 'Width', 'default': 100.0, 'tag': 'wdth', 'maximum': 100.0, 'minimum': 70.0, u'labelname': {u'en': 'Width'}})])
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 28.0, 'Width': 100.0},
 {'Weight': 94.0, 'Width': 100.0},
 {'Weight': 152.0, 'Width': 100.0},
 {'Weight': 194.0, 'Width': 100.0},
 {'Weight': 28.0, 'Width': 70.0},
 {'Weight': 94.0, 'Width': 70.0},
 {'Weight': 152.0, 'Width': 70.0},
 {'Weight': 194.0, 'Width': 70.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [28.0, 94.0, 194.0], 'Width': [70.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': -1.0, 'Width': 0.0},
 {'Weight': 0.0, 'Width': 0.0},
 {'Weight': 0.58, 'Width': 0.0},
 {'Weight': 1.0, 'Width': 0.0},
 {'Weight': -1.0, 'Width': -1.0},
 {'Weight': 0.0, 'Width': -1.0},
 {'Weight': 0.58, 'Width': -1.0},
 {'Weight': 1.0, 'Width': -1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 7, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 2, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.XDeviceTable', 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 2, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.XDeviceTable', 'ItemIndex:', None)
Traceback (most recent call last):
  File "/Users/marek/github/noto-source/env/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/__main__.py", line 248, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 548, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 623, in run_from_designspace
    **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 689, in run_from_ufos
    master_bin_dir=master_bin_dir)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 261, in build_variable_font
    font.save(output_path)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 71, in compile
    return writer.getAllData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 401, in getAllData
    tableData = table.getData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 271, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 2, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.XDeviceTable', 'ItemIndex:', None)

**Comment by marekjez86** [comment]
Similar error for NotoSans-Italic-VF.ttf

INFO:fontmake.font_project:Building variable font variable_ttf/NotoSans-Italic-VF.ttf
INFO:fontTools.varLib:Axes:
OrderedDict([('Weight', {'map': {400.0: 90.0, 600.0: 151.0, 700.0: 190.0, 300.0: 26.0}, 'name': 'Weight', 'default': 400.0, 'tag': 'wght', 'maximum': 700.0, 'minimum': 300.0, u'labelname': {u'en': 'Weight'}}), ('Width', {u'map': None, 'name': 'Width', 'default': 100.0, 'tag': 'wdth', 'maximum': 100.0, 'minimum': 70.0, u'labelname': {u'en': 'Width'}})])
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 26.0, 'Width': 100.0},
 {'Weight': 90.0, 'Width': 100.0},
 {'Weight': 151.0, 'Width': 100.0},
 {'Weight': 190.0, 'Width': 100.0},
 {'Weight': 26.0, 'Width': 70.0},
 {'Weight': 90.0, 'Width': 70.0},
 {'Weight': 151.0, 'Width': 70.0},
 {'Weight': 190.0, 'Width': 70.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [26.0, 90.0, 190.0], 'Width': [70.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': -1.0, 'Width': 0.0},
 {'Weight': 0.0, 'Width': 0.0},
 {'Weight': 0.61, 'Width': 0.0},
 {'Weight': 1.0, 'Width': 0.0},
 {'Weight': -1.0, 'Width': -1.0},
 {'Weight': 0.0, 'Width': -1.0},
 {'Weight': 0.61, 'Width': -1.0},
 {'Weight': 1.0, 'Width': -1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	xhgt: OS/2.sxHeight	[528, 536, 546, 553, 526, 536, 545, 553]
INFO:fontTools.varLib:	stro: OS/2.yStrikeoutPosition	[317, 322, 328, 332, 316, 322, 327, 332]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 4, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 6, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 8, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 7, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 5, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)
Traceback (most recent call last):
  File "/Users/marek/github/noto-source/env/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/__main__.py", line 248, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 548, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 623, in run_from_designspace
    **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 689, in run_from_ufos
    master_bin_dir=master_bin_dir)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 261, in build_variable_font
    font.save(output_path)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 71, in compile
    return writer.getAllData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 401, in getAllData
    tableData = table.getData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 271, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)

**Comment by marekjez86** [comment]
Similar one for NotoSansDisplay-Italic-VF.ttf

INFO:fontmake.font_project:Building variable font variable_ttf/NotoSansDisplay-Italic-VF.ttf
INFO:fontTools.varLib:Axes:
OrderedDict([('Weight', {'map': {400.0: 90.0, 600.0: 151.0, 700.0: 190.0, 300.0: 26.0}, 'name': 'Weight', 'default': 400.0, 'tag': 'wght', 'maximum': 700.0, 'minimum': 300.0, u'labelname': {u'en': 'Weight'}}), ('Width', {u'map': None, 'name': 'Width', 'default': 100.0, 'tag': 'wdth', 'maximum': 100.0, 'minimum': 70.0, u'labelname': {u'en': 'Width'}})])
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 26.0, 'Width': 100.0},
 {'Weight': 90.0, 'Width': 100.0},
 {'Weight': 151.0, 'Width': 100.0},
 {'Weight': 190.0, 'Width': 100.0},
 {'Weight': 26.0, 'Width': 70.0},
 {'Weight': 90.0, 'Width': 70.0},
 {'Weight': 151.0, 'Width': 70.0},
 {'Weight': 190.0, 'Width': 70.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [26.0, 90.0, 190.0], 'Width': [70.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': -1.0, 'Width': 0.0},
 {'Weight': 0.0, 'Width': 0.0},
 {'Weight': 0.61, 'Width': 0.0},
 {'Weight': 1.0, 'Width': 0.0},
 {'Weight': -1.0, 'Width': -1.0},
 {'Weight': 0.0, 'Width': -1.0},
 {'Weight': 0.61, 'Width': -1.0},
 {'Weight': 1.0, 'Width': -1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	xhgt: OS/2.sxHeight	[528, 536, 546, 553, 526, 536, 545, 553]
INFO:fontTools.varLib:	stro: OS/2.yStrikeoutPosition	[317, 322, 328, 332, 316, 322, 327, 332]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 4, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 6, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 8, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)
Traceback (most recent call last):
  File "/Users/marek/github/noto-source/env/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/__main__.py", line 248, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 548, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 623, in run_from_designspace
    **kwargs)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 689, in run_from_ufos
    master_bin_dir=master_bin_dir)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontmake/font_project.py", line 261, in build_variable_font
    font.save(output_path)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 71, in compile
    return writer.getAllData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 401, in getAllData
    tableData = table.getData()
  File "/Users/marek/github/noto-source/env/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 271, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)

**Comment by marekjez86** [comment]
NotoSerifDisplay-Italic-VF.ttf
NotoSans-Italic-VF.ttf
NotoSansDisplay-Italic-VF.ttf
NotoSansDisplay-VF.ttf

**Comment by anthrotype** [comment]
Thanks Marek, I'll investigate.

**Comment by anthrotype** [comment]
@behdad I wonder what's the status of that "99-proof small-batch distillery" algorithm of yours to fix offset overflows. Maybe it's more resilient to subtables like these ones.

**Comment by anthrotype** [comment]
I'm able to reproduce.
The offset overflow is happening inside a GPOS MarkBasePos subtable, as can be seen from the last line of the traceback:

```
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 3, 'SubTableIndex:', 0, 'ItemName:', 'MarkArray.MarkAnchor.YDeviceTable', 'ItemIndex:', None)
```

It looks like fonttools doesn't know how to split an overflowing MarkBasePos subtable... :(

https://github.com/fonttools/fonttools/blob/87178f413a97bd725c7a62e0c89108933e35c746/Lib/fontTools/ttLib/tables/otTables.py#L1298

https://github.com/fonttools/fonttools/blob/87178f413a97bd725c7a62e0c89108933e35c746/Lib/fontTools/ttLib/tables/otTables.py#L1347-L1350

I'll talk with @bedad when I meet him in Madrid next week on how to go about solving this.

**Comment by anthrotype** [comment]
I think this is also related to the new ufo2ft MarkFeatureWriter which creates a single mark2base lookup instead of one lookup per markClass.
https://github.com/googlei18n/ufo2ft/issues/259

**Comment by behdad** [comment]
It's trivial to split that subtable. We can fix on Monday.
