### ISSUE TITLE
ImportError: No module named interpolation

### ISSUE THREAD

**Issue by miguelsousa** [googlei18n/fontmake#451]
fontmake version 1.6.0
```
$ fontmake -m SourceSerifVariable-Roman.designspace -o variable
Traceback (most recent call last):
  File "fontmake/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "fontmake/lib/python2.7/site-packages/fontmake/__main__.py", line 256, in main
    project.run_from_designspace(designspace_path, **args)
  File "fontmake/lib/python2.7/site-packages/fontmake/font_project.py", line 585, in run_from_designspace
    from glyphsLib.interpolation import apply_instance_data
ImportError: No module named interpolation
```

**Comment by anthrotype** [comment]
this was the result of https://github.com/googlei18n/glyphsLib/pull/361

the `glyphsLib.interpolation` module was removed. The `apply_instance_data` function is still defined in `glyphsLib.builder.instances`. I'll change next version of fontmake to import from there.

For now you can install the previous glyphsLib version preceding 3.0.0, `pip install glyphsLib==2.4.0`

**Comment by anthrotype** [comment]
in the end I decided to fix this in glyphsLib, instead of here in fontmake.
