### ISSUE TITLE
fontmake fails with simple 5-master setup

### ISSUE THREAD

**Issue by twardoch** [googlei18n/fontmake#454]
I’ve been trying to turn these simple designspaces into a variable font, with no luck: [Archive.zip](https://github.com/googlei18n/fontmake/files/2225152/Archive.zip)

I get this output which I don’t really understand: 

```
fontmake -m Test.designspace -o variable
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths:
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Unnamed-Regular
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Test-ThinExpanded
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Test-BlackExpanded
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Test-ThinCondensed
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Test-BlackCondensed
INFO:ufo2ft:Building OpenType tables for Unnamed-Regular
INFO:fontmake.font_project:Saving /var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/ttf-interp-bznABA/Test-Regular.ttf
INFO:ufo2ft:Building OpenType tables for Test-ThinExpanded
INFO:fontmake.font_project:Saving /var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/ttf-interp-bznABA/Test-ThinExpanded.ttf
INFO:ufo2ft:Building OpenType tables for Test-BlackExpanded
INFO:fontmake.font_project:Saving /var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/ttf-interp-bznABA/Test-BlackExpanded.ttf
INFO:ufo2ft:Building OpenType tables for Test-ThinCondensed
INFO:fontmake.font_project:Saving /var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/ttf-interp-bznABA/Test-ThinCondensed.ttf
INFO:ufo2ft:Building OpenType tables for Test-BlackCondensed
INFO:fontmake.font_project:Saving /var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/ttf-interp-bznABA/Test-BlackCondensed.ttf
INFO:fontmake.font_project:Building variable font variable_ttf/Test-VF.ttf
INFO:fontTools.varLib:Axes:
OrderedDict([('weight', {u'map': None, 'name': 'weight', 'default': 400.0, 'tag': 'wght', 'maximum': 900.0, 'minimum': 100.0, 'labelname': {'en': 'Weight'}}), ('width', {u'map': None, 'name': 'width', 'default': 100.0, 'tag': 'wdth', 'maximum': 120.0, 'minimum': 75.0, 'labelname': {'en': 'Width'}})])
INFO:fontTools.varLib:Internal master locations:
[{'weight': 400.0, 'width': 100.0},
 {'weight': 900.0, 'width': 75.0},
 {'weight': 100.0, 'width': 120.0},
 {'weight': 100.0, 'width': 75.0},
 {'weight': 900.0, 'width': 120.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [100.0, 400.0, 900.0], 'width': [75.0, 100.0, 120.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': 0.0, 'width': 0.0},
 {'weight': 1.0, 'width': -1.0},
 {'weight': -1.0, 'width': 1.0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 1.0, 'width': 1.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
Traceback (most recent call last):
  File "/Users/adam/Library/Python/2.7/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontmake/__main__.py", line 256, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 623, in run_from_designspace
    **kwargs)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 689, in run_from_ufos
    master_bin_dir=master_bin_dir)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 259, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 759, in build
    model = models.VariationModel(normalized_master_locs, axisOrder=axisTags)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/models.py", line 169, in __init__
    self.locations = sorted(locations, key=keyFunc)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/models.py", line 197, in key
    onPointAxes = [axis for axis,value in loc.items() if value in axisPoints[axis]]
KeyError: 'wdth'
```

**Comment by miguelsousa** [comment]
I think `u'map': None` in the `OrderedDict` means that the `<map>` elements didn't get loaded.
Try removing the `<labelname>` elements from the designspace file.

**Comment by miguelsousa** [comment]
Scratch that. What you need to do is add `map` elements to the `width` axis. See https://github.com/googlei18n/fontmake/issues/401#issuecomment-367255986.

**Comment by behdad** [comment]
Currently we require that each axis have masters on its extremes.  So, you need 9 :(.  What you request is very legitimate.  The way to do it is that internally we should synthesize the four missing axis extremes and add them to the system...

There's a hack also that I wouldn't go into since it wouldn't work cross platform (or on any platform).

**Comment by twardoch** [comment]
Oh, right, stupid me, this is the X master setup while we need ✢ or ❋. Of course. I mean, yeah, it would be nice to support the X config via interpolation of intermediate on-axis masters — but  I should have realized it.

**Comment by behdad** [comment]
Yep. :)

**Comment by typoland** [comment]
As far I know adding intermediate instances is not so simple if in space (-1,-1)(-1,0)(0,-1)(1,1) are more than one additional master - (0,0) and (something, something). In more than two dimensional fonts it’s even more difficult.

**Comment by thundernixon** [comment]
I'm trying to do something slightly similar, and getting a similar error. 

I'm hoping to make a simple family with a "weight" axis from two masters, and then also a "grade" axis from a third master, with deltas simply pushing the points inward by a bit. A ["grade" axis](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#Grade) is a bit like weight, but without changing metrics. It is usually fairly subtle, used to account for different light/color contexts. Because it's subtle, it seems that A) it would be a shame to add two extra sets of deltas to the variable font for it, and B) it probably _could_ work, mathematically and visually, with just one set of deltas. Here's my basic setup in Glyphs, and a simple example of how Glyphs can synthesize the "Bold Grade" instances:

![image](https://user-images.githubusercontent.com/7355414/47242329-606f0100-d3bc-11e8-8420-9134a1b77b3a.png)

However, with just three masters, if I try to export to a VF, FontMake fails and I get the error message `KeyError: 'wght'`. 

If I have four masters, however, it works as expected:

![grade-expectations](https://user-images.githubusercontent.com/7355414/47242758-cb6d0780-d3bd-11e8-9a95-3641f027d2fc.gif)

Is it still correct that it is currently not possible to export a variable font without a "fully-cornered" designspace, with each axis having masters on its extremes? If so, is this kind of thing expected to change soon-ish, or ever? I know there's a lot going on; I just want to make sure I'm not jumping to conclusions before I give up on the 3-master approach, and I'm posting so that others can find this if they run into a similar error message. Thanks for any insight or update!

**Comment by davelab6** [comment]
Isn't the "3 masters" set up possible when the grade axis doesn't have a max, aka, the max _is_ default, using `<map`>?

```
wght-min -------- default -------- wght-max

grad-min -------- default
```

Effectively forming an isosceles triangle design space

```
wght-min -------- default -------- wght-max
                    |
                    |
                    |
                  grad-min
```

**Comment by thundernixon** [comment]
Thanks, Dave – it works with that slight change! 

I was trying to do almost exactly that, _but_ I had the grad-min set as the default, rather than the grad-max. My designspace looked like this, however, where the min `wght` was the default. 

It's now exporting and is 175kb for the TTF, versus the 206kb that 4 masters produced.

![3-master-vf](https://user-images.githubusercontent.com/7355414/47258845-7093e880-d46f-11e8-9f93-62f5f641dc75.gif)

Just to make it clear for others, this seems to be working well:

```
    <axes>
        <axis default="300" maximum="750" minimum="300" name="Weight" tag="wght">
            # (I'll be tweaking these map values more, so they're not final)
            <map input="300" output="0" />
            <map input="400" output="360" />
            <map input="600" output="650" />
            <map input="700" output="920" />
            <map input="750" output="1000" />
        </axis>


        #################

        # this is the critical bit – the default *must* match the GRAD of the two main masters for wght

        <axis default="100" maximum="100" minimum="0" name="Grade" tag="GRAD" />

        #################

    </axes>

    # here are my 3 sources
    <sources>
        <source familyname="Signika" filename="Signika-Light-GRAD.ufo" name="Signika Light-GRAD" stylename="Light-GRAD">
            <lib copy="1" />
            <groups copy="1" />
            <features copy="1" />
            <info copy="1" />
            <location>
                <dimension name="Weight" xvalue="0" />
                <dimension name="Grade" xvalue="0" />
            </location>
        </source>
        <source familyname="Signika" filename="Signika-Light.ufo" name="Signika Light" stylename="Light">
            <location>
                <dimension name="Weight" xvalue="0" />
                <dimension name="Grade" xvalue="100" />
            </location>
        </source>
        <source familyname="Signika" filename="Signika-Bold.ufo" name="Signika Bold" stylename="Bold">
            <location>
                <dimension name="Weight" xvalue="1000" />
                <dimension name="Grade" xvalue="100" />
            </location>
        </source>
    </sources>
```

🎉
