### ISSUE TITLE
ImportError: cannot import name basestring

### ISSUE THREAD

**Issue by joachimvu** [googlei18n/fontmake#487]
Getting this trying to run fontmake:
Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/bin/fontmake", line 7, in <module>
    from fontmake.__main__ import main
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/fontmake/__main__.py", line 19, in <module>
    from fontmake.font_project import FontProject
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 41, in <module>
    from defcon import Font
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/defcon/__init__.py", line 10, in <module>
    from defcon.objects.font import Font
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/defcon/objects/font.py", line 6, in <module>
    from fontTools.misc.py23 import basestring
ImportError: cannot import name basestring

**Comment by anthrotype** [comment]
@joachimvu this is weird. It seems you are using an outdated version of fonttools.
can you paste here the output of `pip list`?

Try to upgrade fontmake and its dependencies to the current version, with `python -m pip install --upgrade fontmake`? Replace `python` with the name of the python interpreter you want to install fontmake to.
