### ISSUE TITLE
pipeline regression: allmost of all my test runs produce stack trace AttributeError: 'str' object has no attribute 'getReverseGlyphMap'

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#51]
The last time I updated and ran pipeline was about 2 days ago. At that time I had no problems like this one.

Here's the input file that causes the problem below 
[mzjArimo-Regular.glyphs.zip](https://github.com/googlei18n/fontmake/files/188667/mzjArimo-Regular.glyphs.zip)

I can submit many more input files.

This is the stack trace:

```
==== building src/mzjArimo-Regular.glyphs ====
/usr/local/lib/python2.7/dist-packages/mutatorMath/ufo/instance.py:199: UserWarning: MathInfo object missing round() method.
  warnings.warn("MathInfo object missing round() method.")
>> Checking Glyphs source for illegal glyph names
>> Interpolating master UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to RFonts
>>> Writing masters
>>> Building instances
>> Removing overlaps for Arimo-Regular
>> Saving OTF for Arimo-Regular
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 51, in <module>
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 39, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 184, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 212, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 120, in save_otf
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 29, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 18, in _compile
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 40, in compile
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 188, in setupFile_featureTables
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 15, in addOpenTypeFeatures
    builder = Builder(font, featurefile)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 32, in __init__
    self.glyphMap = font.getReverseGlyphMap()
AttributeError: 'str' object has no attribute 'getReverseGlyphMap'
```

**Comment by marekjez86** [comment]
If you need I can also provide you with an input that didn't crash. 

So far I ran 36 tests: 8 of them produced output without crashing and 28 of them produced the same AttributeError: 'str' object has no attribute 'getReverseGlyphMap'

marekj@yol-worjdp:~/src/noto-source$ grep "Saving TTF" makeout-201603241332.txt |  wc -l
8
marekj@yol-worjdp:~/src/noto-source$ grep "object has no attribute" makeout-201603241332.txt |  wc -l
28

**Comment by jamesgk** [comment]
I'm guessing this is related to https://github.com/googlei18n/ufo2ft/pull/29. The pipeline has been in somewhat of an unstable state due to some updates to the feaLib API. But I believed that with all the dependencies updated as of today, it should be working (it is for me). Did you run `make setup` in noto-source?

**Comment by jamesgk** [comment]
Hmm, I see from the stack trace that FontTools is located in a system-install directory while everything else is not. So I guess `make setup` is updating dependencies in a local directory, but the system (outdated) FontTools is being used. So I think this is a noto-source issue, not fontmake.

**Comment by marekjez86** [comment]
I assume that could be an issue with one of my path variables. Let me look around.

**Comment by marekjez86** [comment]
closing the bug as a user PATH error (aka this user "messed up" :-))
