### ISSUE TITLE
v1.9.0: TypeError: save_otfs() got an unexpected keyword argument 'expand_features_to_instances'

### ISSUE THREAD

**Issue by santhoshtr** [googlei18n/fontmake#515]
In a fresh venv, I get the following error:

```
Traceback (most recent call last):
  File "/home/santhosh/work/fonts/Gayathri/ENV_DIR/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/santhosh/work/fonts/Gayathri/ENV_DIR/lib/python3.6/site-packages/fontmake/__main__.py", line 395, in main
    ufo_paths, is_instance=args.pop("masters_as_instances"), **args
  File "/home/santhosh/work/fonts/Gayathri/ENV_DIR/lib/python3.6/site-packages/fontmake/font_project.py", line 974, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/home/santhosh/work/fonts/Gayathri/ENV_DIR/lib/python3.6/site-packages/fontmake/font_project.py", line 269, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/home/santhosh/work/fonts/Gayathri/ENV_DIR/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
TypeError: save_otfs() got an unexpected keyword argument 'expand_features_to_instances'
make: *** [Makefile:25: build/Gayathri-Regular.otf] Error 1
```

**Comment by madig** [comment]
Oops. Fix on the way.
