### ISSUE TITLE
feaTools.parser.FeaToolsParserSyntaxError: u'lookupflag format B is not supported for any value other than 0'

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#54]
I got this error while processing, using pipeline delivery, of [Noto Serif Hebrew](https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifHebrew-MM.glyphs) font.

Is this a fontmake issue or a problem with the delivered files or a compatibility issue?

< >>> Parsing .glyphs file
< >>> Casting parsed values
< >>> Loading to RFonts
< >>> Writing masters
< >>> Building instances
< >> Removing overlaps for NotoSerifHebrew-Thin
< >> Removing overlaps for NotoSerifHebrew-Light
< >> Removing overlaps for NotoSerifHebrew-Regular
< >> Removing overlaps for NotoSerifHebrew-SemiBold
< >> Removing overlaps for NotoSerifHebrew-Bold
< >> Removing overlaps for NotoSerifHebrew-ExtraBold
< >> Removing overlaps for NotoSerifHebrew-Black
< >> Removing overlaps for NotoSerifHebrewCondensed-Thin
< >> Removing overlaps for NotoSerifHebrewCondensed-Light
< >> Removing overlaps for NotoSerifHebrewCondensed-Regular
< >> Removing overlaps for NotoSerifHebrewCondensed-SemiBold
< >> Removing overlaps for NotoSerifHebrewCondensed-Bold
< >> Removing overlaps for NotoSerifHebrewCondensed-ExtraBold
< >> Removing overlaps for NotoSerifHebrewCondensed-Black
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-Thin
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-Light
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-Regular
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-SemiBold
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-Bold
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-ExtraBold
< >> Removing overlaps for NotoSerifHebrewSemiCondensed-Black
< >> Saving OTF for NotoSerifHebrew-Thin
< Traceback (most recent call last):
<   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
<     "__main__", fname, loader, pkg_name)
<   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
<     exec code in run_globals
<   File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 51, in <module>
<   File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 39, in main
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 184, in run_from_glyphs
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 212, in run_from_ufos
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 120, in save_otf
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 29, in compileOTF
<     featureCompilerClass, mtiFeaFiles, kernWriter, markWriter)
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 18, in _compile
<     featureCompiler.compile()
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 37, in compile
<     self.setupFile_features()
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 73, in setupFile_features
<     autoFeatures["kern"] = self.writeFeatures_kern()
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 97, in writeFeatures_kern
<     return writer.write()
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/kernFeatureWriter.py", line 61, in write
<     self._collectFeaClasses()
<   File "/usr/local/lib/python2.7/dist-packages/ufo2ft/kernFeatureWriter.py", line 99, in _collectFeaClasses
<     parser.parseFeatures(self, self.featxt)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 657, in parseFeatures
<     _parseUnknown(writer, text)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 309, in _parseUnknown
<     _parseFeature(writer, featureTag, featureText)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 438, in _parseFeature
<     parsed = _parseUnknown(featureWriter, feature)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 327, in _parseUnknown
<     _parseLookup(writer, lookupName, lookupText)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 442, in _parseLookup
<     parsed = _parseUnknown(lookupWriter, lookup)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 339, in _parseUnknown
<     text = _executeSimpleSlice(precedingMark, text, subType1And4RE, writer)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 432, in _executeSimpleSlice
<     _parseUnknown(writer, precedingText)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 407, in _parseUnknown
<     _parseLookupFlag(writer, lookupflagValues)
<   File "/usr/local/lib/python2.7/dist-packages/feaTools/parser.py", line 621, in _parseLookupFlag
<     raise FeaToolsParserSyntaxError("lookupflag format B is not supported for any value other than 0")
< feaTools.parser.FeaToolsParserSyntaxError: u'lookupflag format B is not supported for any value other than 0'

**Comment by marekjez86** [comment]
I'm unable to reproduce it after I rebuilt the pipeline on Thursday 2016-03-31 evening (about 10pm PDT)
The problem was either fixed or my build problem.

now my diff of logs says

8175,8361c8175,8217
< >> Saving OTF for NotoSerifHebrew-Light
< >> Saving OTF for NotoSerifHebrew-Regular
< >> Saving OTF for NotoSerifHebrew-SemiBold
< >> Saving OTF for NotoSerifHebrew-Bold
< >> Saving OTF for NotoSerifHebrew-ExtraBold
< >> Saving OTF for NotoSerifHebrew-Black
< >> Saving OTF for NotoSerifHebrewCondensed-Thin
< >> Saving OTF for NotoSerifHebrewCondensed-Light
< >> Saving OTF for NotoSerifHebrewCondensed-Regular
< >> Saving OTF for NotoSerifHebrewCondensed-SemiBold
< >> Saving OTF for NotoSerifHebrewCondensed-Bold
< >> Saving OTF for NotoSerifHebrewCondensed-ExtraBold
< >> Saving OTF for NotoSerifHebrewCondensed-Black
< >> Saving OTF for NotoSerifHebrewSemiCondensed-Thin
< >> Saving OTF for NotoSerifHebrewSemiCondensed-Light
< >> Saving OTF for NotoSerifHebrewSemiCondensed-Regular
< >> Saving OTF for NotoSerifHebrewSemiCondensed-SemiBold
< >> Saving OTF for NotoSerifHebrewSemiCondensed-Bold
< >> Saving OTF for NotoSerifHebrewSemiCondensed-ExtraBold
< >> Saving OTF for NotoSerifHebrewSemiCondensed-Black
< >> Converting curves for NotoSerifHebrew-Thin
< New spline lengths:
< 3: 1042
< 4: 377
< 5: 8
< 6: 9
.......... and many more
