### ISSUE TITLE
glyphs file compatibility issue: unescaped quote in license string causes traceback

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#56]
[NotoSansThaiUI-MM.Glyphs.zip](https://github.com/googlei18n/fontmake/files/203610/NotoSansThaiUI-MM.Glyphs.zip)

I'm not certain how the above input file was produced, but Glyphs.app handles it.
The issue is with the unescaped " in the license attribute.

The file above has:
_This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions and limitations governing your use of this Font Software.
_where "AS IS" is not presented as \"AS IS\" like in the previous inputs.

We produce a traceback. Glyphs.app does not.

```
~/rel/noto-source$ make -B src/NotoSansThaiUI-MM.glyphs
bash build.sh build_one src/NotoSansThaiUI-MM.glyphs
>> Checking Glyphs source for illegal glyph names
Found 123 glyph names containing hyphens: angkhankhu-thai, boBaimai-thai, choChan-thai, choChang-thai, choChing-thai, ...
Replacing all hyphens with underscores.
>> Interpolating master UFOs from Glyphs source
>>> Parsing .glyphs file
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 51, in <module>
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 39, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 179, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 77, in build_instances
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/glyphslib.py", line 101, in build_instances
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/glyphslib.py", line 57, in load_to_ufos
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/glyphslib.py", line 38, in load
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/glyphslib.py", line 47, in loads
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 39, in parse
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 51, in _parse
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 79, in _parse_dict
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 57, in _parse
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 100, in _parse_list
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 51, in _parse
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 84, in _parse_dict
  File "build/bdist.linux-x86_64/egg/glyphs2ufo/parser.py", line 130, in _fail
ValueError: Missing delimiter in dictionary before content:
AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or i
make: *** [src/NotoSansThaiUI-MM.glyphs] Error 1
```

**Comment by jamesgk** [comment]
Thanks. Moving issue to glyphsLib.
