### ISSUE TITLE
mti sources are not handled correctly

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#62]
I spent the afternoon debugging why I'm not getting any GSUB/GPOS/GDEF out of the pipeline, turned out to be because of https://github.com/googlei18n/fontmake/commit/9c2ae2d6ee984b82ab2db741fdccf800e20b4061

while fixing that, I also made a change to how mti sources are consumed: https://github.com/googlei18n/fontmake/commit/1e2a639788a8d06564d1fe46a43d2e1bed03bb14

that exposed another bug.  Copying from the commit message there:
```
Make mti-sources processing more strict
If --mti-sources is provided, then it MUST declare mti sources for
all masters, so don't silently fallback to automatic feature
generation.

In fact, this exposed a bug in fontmake.  When running against
NotoSansDevanagari sources, we now get:

>> Saving OTF for NotoSansDevanagari-Light
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 42, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 221, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 258, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 113, in build_otfs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 157, in save_otfs
KeyError: 'NotoSansDevanagari-Light'

That is because the sources call this font Thin, and the plist has that
and the mti-sources are called that.  But fontmake ignored the name
of the master and replaced it with Light, and is looking for Light.

That should be fixed separately.
```

**Comment by behdad** [comment]
cc @marekjez86

**Comment by jamesgk** [comment]
I don't think this is a bug, the Devanagari features in noto-source are meant to be applied to instances, while here they're being applied to masters. Now, they do currently have an issue when applied to instances, which I'm submitting PRs to fix.

**Comment by jamesgk** [comment]
Should be fixed.
