### ISSUE TITLE
TTF building fails on a test file that works with glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#82]
As an input use any AV*.glyphs file from
[Glyphs-AV-kerningTest.zip](https://github.com/googlei18n/fontmake/files/276201/Glyphs-AV-kerningTest.zip)

I obtained this file from https://github.com/googlei18n/glyphsLib/issues/24

OTF is produced but TTF fails.

```
> Saving TTF for AV-Regular
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 61, in <module>
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 229, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 280, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 145, in build_ttfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 175, in save_otfs
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 32, in compileTTF
    the options kwargs. They are:
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 23, in compileOTF
    Usage (python):
  File "build/bdist.linux-x86_64/egg/ufo2ft/otfPostProcessor.py", line 15, in __init__
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 645, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 645, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_g_l_y_f.py", line 82, in compile
    glyph = self.glyphs[glyphName]
KeyError: u'.notdef'
make: *** [src/AV1.glyphs] Error 1
```

**Comment by jamesgk** [comment]
I think it's fair to assume that all input will contain a .notdef glyph. But we can at least fail more gracefully.

**Comment by behdad** [comment]
While inserting .notdef if that's not available in the font sounds like a good idea, I don't think we should fail if it's not available.

Also, in ufo2ft, I see we try to add space if missing as well.  That I think should not happen.

**Comment by adrientetar** [comment]
Agreed.

**Comment by jamesgk** [comment]
> Also, in ufo2ft, I see we try to add space if missing as well. That I think should not happen.

I guess that's because of this code:
https://github.com/googlei18n/ufo2ft/blob/master/Lib/ufo2ft/outlineOTF.py#L491

not sure if there's a better way to handle this case.

**Comment by adrientetar** [comment]
> not sure if there's a better way to handle this case.

AFDKO [fallbacks to 0xFFFF](https://github.com/adobe-type-tools/afdko/blob/230c0b6dec09efb7a340f97f237123c7ed13e6d6/FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/map.c#L1715), we should probably match it. @behdad was previously thinking that using 0x0000 as fallback could be the more obvious choice.

**Comment by marekjez86** [comment]
Verified as fixed.
