### ISSUE TITLE
Space are not allowed in glyph names: standard says they should be

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#86]
the following quoted paragraph was copied from http://monotype.github.io/OpenType_Table_Source/otl_source.html#glyph-references

"Glyph References
Glyphs are usually represented by their name from the ‘post’ table or ‘CFF ‘ table. If there is no format 2 post table or no names stored in the ‘CFF ‘ table then it is possible to refer to glyphs by Unicode or by glyph index.

To refer to a glyph by Unicode use U or u followed by a space, followed by the hexadecimal Unicode. To refer to a glyph by index use a # followed by a space followed by the index in decimal. For example: in a normal Latin font in standard order the lowercase a can be referred to in the following ways:

a
U 0061
u 0061
\# 68
"

Based on the above the following four lines refer to the same item:
a
U 0061
u 0061
\# 68

But here is the from a pipeline execution which 
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 369, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 21, in compileOTF
    featureCompiler.compile()
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 38, in compile
    self.setupFile_featureTables()
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 169, in setupFile_featureTables
    table = mtiLib.build(feafile, self.outline)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 1089, in build
    return parseTable(lines, font, tableTag=tableTag)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 988, in parseTable
    }[tableTag](lines, font)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 893, in parseGSUB
    return parseGSUBGPOS(lines, font, 'GSUB')
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 874, in parseGSUBGPOS
    lookup = parseLookup(lines, tableTag, font, lookupMap)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 830, in parseLookup
    parseLookupSubTable(subtable, lines, font, lookupMap)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 756, in parseContextSubst
    return parseContext(self, lines, font, "ContextSubst", lookupMap=lookupMap)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 713, in parseContext
    classDefs[idx] = parseClassDef(lines, klass=klass)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 634, in parseClassDef
    glyph = makeGlyph(line[0])
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/mtiLib/__init__.py", line 35, in makeGlyph
    assert s.find(' ') < 0, "Space found in glyph name: %s" % s
AssertionError: Space found in glyph name: u 200D

**Comment by behdad** [comment]
Thanks.  Please try again and let me know if it worked.

**Comment by behdad** [comment]
Which font was this with?

**Comment by marekjez86** [comment]
I cannot validate it. It was with a font under development by MTI (they were preparing it to send to us). They just sent me the stack trace. I'll advise them to pull new pipeline and re-run it.

**Comment by behdad** [comment]
Ah, I see.  In general we prefer if they use actual glyph names instead of using the "U " or "u " syntax.  But let's see, maybe it works. :)

**Comment by marekjez86** [comment]
I think they used uniXXXX or {u,U}XXXX as the name as a workaround, but
I'll ask them to test the update.

On Wed, Jun 8, 2016 at 3:28 PM, Behdad Esfahbod <notifications@github.com>
wrote:

> Ah, I see. In general we prefer if they use actual glyph names instead of
> using the "U " or "u " syntax. But let's see, maybe it works. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/86#issuecomment-224749782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMtJf6DzC7tKj3zLfv9H6m1e2xII1L7Tks5qJ0IggaJpZM4Itypi>
> .
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by marekjez86** [comment]
verification of the fix from the person that originally encountered the problem: "Confirmed @behdad 's fix worked on the font that reported the trackback - no trackback and font files were built"
