### ISSUE TITLE
AssertionError with a test input mzjTinos-Regular.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#89]
1. I took https://github.com/googlei18n/noto-fonts/blob/master/hinted/Tinos-Regular.ttf font and imported into a Glyphs.app on my Mac (I've done it a while ago; I got an update to the Glyphs.app since then)
2. Exported/Saved from Glyphs.app as mzjTinos-Regular.glyphs  without changing anything in the fonts
[mzjTinos-Regular.glyphs.zip](https://github.com/googlei18n/fontmake/files/310667/mzjTinos-Regular.glyphs.zip)

3. I fed mzjTinos-Regular.glyphs to the fontmake hoping to get back exactly the same Tinos-Regular.ttf font that I fed to the Glyphs.app

Unfortunately it crashed.

marekj@yol-worjdp:~/src2/noto-source$ make -B src/mzjTinos-Regular.glyphs
bash build.sh build_one src/mzjTinos-Regular.glyphs
>> Checking Glyphs source for illegal glyph names
>> Building UFOs from Glyphs source
>>> Parsing .glyphs file
>>> Casting parsed values
>>> Loading to UFOs
>>> Writing master_ufo/Tinos-Regular.ufo
>>> Building instances

>> Building OTFs
>> Decomposing glyphs for Tinos-Regular
>> Removing overlaps for Tinos-Regular
>> Saving OTF for Tinos-Regular
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 24, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/otfPostProcessor.py", line 25, in process
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 115, in compress
    self.run_executable()
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 135, in run_executable
    cxxCompressor.compreff(self.font, use_lib=False, **self.options)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 248, in compreff
    subrs, glyph_encodings = read_data(td, results)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 152, in read_data
    assert pos == len(results)
AssertionError
make: *** [src/mzjTinos-Regular.glyphs] Error 1

**Comment by behdad** [comment]
Someone needs to debug this one.

**Comment by marekjez86** [comment]
unable to reproduce. right now I can build source in mzjTinos-Regular.glyphs.zip
appears to be fixed
